lang__fr = Language.create({name: 'Français', shorthand: 'fr', active: true, has_gendered_nouns: true})
lang__en = Language.create({name: 'English', shorthand: 'en', active: true, has_gendered_nouns: false})
lang__es = Language.create({name: 'Español', shorthand: 'es', active: true, has_gendered_nouns: true})
lang__ca = Language.create({name: 'Catalan', shorthand: 'ca', active: false, has_gendered_nouns: true})
lang__no = Language.create({name: 'Norsk', shorthand: 'no', active: false, has_gendered_nouns: false})