gender__neutral = Gender.create(name: "Neutre", shorthand: "n")
gender__male = Gender.create(name: "Masculin", shorthand: "m")
gender__female = Gender.create(name: "Féminin", shorthand: "f")
gender__object = Gender.create(name: "Object", shorthand: "o")
gender__plural = Gender.create(name: "Pluriel", shorthand: "p")
gender__mixed = Gender.create(name: "Mixte", shorthand: "all")
gender__unknown = Gender.create(name: "Inconnu", shorthand: "?")