# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
lang__en = Language.create({name: 'English', shorthand: 'en', active: true})
lang__fr = Language.create({name: 'Français', shorthand: 'fr', active: true})
lang__es = Language.create({name: 'Español', shorthand: 'es', active: true})
lang__ca = Language.create({name: 'Catalan', shorthand: 'ca', active: true})
lang__no = Language.create({name: 'Norsk', shorthand: 'no', active: true})

region__spain = Region.create({name: "Spain", shorthand: "esp", description: ""})
region__latam = Region.create({name: "Latin America", shorthand: "latam", description: ""})
region__mexico = Region.create({name: "Mexico", shorthand: "mx", description: ""})
region__argentina = Region.create({name: "Argentina", shorthand: "ar", description: ""})

verb_mood__infinitive = VerbMood.create({name: "Infinitive"})
verb_mood__indicative = VerbMood.create({name: "Indicative"})
verb_mood__subjonctive = VerbMood.create({name: "Subjonctive"})
verb_mood__conditional = VerbMood.create({name: "Conditional"})
verb_mood__imperative = VerbMood.create({name: "Imperative"})

word_class__article     = WordClass.create({name: "Article"})
word_class__noun        = WordClass.create({name: "Noun"})
word_class__verb        = WordClass.create({name: "Verb"})
word_class__adverb      = WordClass.create({name: "Adverb"})
word_class__pronoun     = WordClass.create({name: "Pronoun"})
word_class__preposition = WordClass.create({name: "Preposition"})
word_class__conjunction = WordClass.create({name: "Conjunction"})
word_class__expression  = WordClass.create({name: "Expression"})
word_class__adjective   = WordClass.create({name: "Adjective"})

words = Word.create([(1,1,'el',lang__es,2),
    { name:(word_class__article,'la',lang__es,1) },
    { name:(word_class__article,'le',lang__fr,2) },
    { name:(word_class__article,'la',lang__fr,1) },
    { name:(word_class__article,'las',lang__es,3) },
    { name:(word_class__article,'los',lang__es,4) },
    { name:(word_class__article,'les',lang__fr,3) },
    { name:(word_class__article,'les',lang__fr,4) },
    { name:(word_class__article,'una',lang__es,5) },
    { name:(word_class__article,'un',lang__es,6) },
    { name:(word_class__article,'une',lang__fr,5) },
    { name:(word_class__article,'un',lang__fr,6) },
    { name:(word_class__verb,'ser',lang__es,7) },
    { name:(word_class__verb,'être',lang__fr,7) },
    { name:(word_class__verb,'to be',lang__en,7) },
    { name:(word_class__verb,'estar',lang__es,8) },
    { name:(word_class__verb,'être',lang__fr,8) },
    { name:(word_class__verb,'to be',lang__en,8) },
    { name:(word_class__verb,'parecer',lang__es,9) },
    { name:(word_class__verb,'paraître',lang__fr,9) },
    { name:(word_class__verb,'to seem',lang__en,9) },
    { name:(word_class__verb,'deber',lang__es,10) },
    { name:(word_class__verb,'devoir',lang__fr,10) },
    { name:(word_class__verb,'querer',lang__es,11) },
    { name:(word_class__verb,'vouloir',lang__fr,11) },
    { name:(word_class__verb,'to want',lang__en,11) },
    { name:(word_class__verb,'saber',lang__es,12) },
    { name:(word_class__verb,'savoir',lang__fr,12) },
    { name:(word_class__verb,'to know',lang__en,12) },
    { name:(word_class__verb,'poder',lang__es,13) },
    { name:(word_class__verb,'pouvoir',lang__fr,13) },
    { name:(word_class__verb,'to be able to',lang__en,13) },
    { name:(word_class__verb,'sentar',lang__es,14) },
    { name:(word_class__verb,'asseoir',lang__fr,14) },
    { name:(word_class__verb,'to sit',lang__en,14) },
    { name:(word_class__verb,'levantar',lang__es,15) },
    { name:(word_class__verb,'lever',lang__fr,15) },
    { name:(word_class__verb,'to get up',lang__en,15) },
    { name:(word_class__verb,'caminar',lang__es,16) },
    { name:(word_class__verb,'marcher',lang__fr,16) },
    { name:(word_class__verb,'to walk',lang__en,16) },
    { name:(word_class__verb,'correr',lang__es,17) },
    { name:(word_class__verb,'courir',lang__fr,17) },
    { name:(word_class__verb,'to run',lang__en,17) },
    { name:(word_class__verb,'nadar',lang__es,18) },
    { name:(word_class__verb,'nager',lang__fr,18) },
    { name:(word_class__verb,'to swim',lang__en,18) },
    { name:(word_class__verb,'volar',lang__es,19) },
    { name:(word_class__verb,'voler',lang__fr,19) },
    { name:(word_class__verb,'to fly',lang__en,19) },
    { name:(word_class__verb,'bailar',lang__es,20) },
    { name:(word_class__verb,'danser',lang__fr,20) },
    { name:(word_class__verb,'to dance',lang__en,20) },
    { name:(word_class__verb,'girar',lang__es,21) },
    { name:(word_class__verb,'tourner',lang__fr,21) },
    { name:(word_class__verb,'to turn',lang__en,21) },
    { name:(word_class__verb,'andar',lang__es,22) },
    { name:(word_class__verb,'promener',lang__fr,22) },
    { name:(word_class__verb,'to walk',lang__en,22) },
    { name:(word_class__verb,'llover',lang__es,23) },
    { name:(word_class__verb,'pleuvoir',lang__fr,23) },
    { name:(word_class__verb,'to rain',lang__en,23) },
    { name:(word_class__verb,'nevar',lang__es,23) },
    { name:(word_class__verb,'neiger',lang__fr,23) },
    { name:(word_class__verb,'to snow',lang__en,23) },
    { name:(word_class__verb,'vivir',lang__es,24) },
    { name:(word_class__verb,'vivre',lang__fr,24) },
    { name:(word_class__verb,'to live',lang__en,24) },
    { name:(word_class__verb,'ir',lang__es,25) },
    { name:(word_class__verb,'aller',lang__fr,25) },
    { name:(word_class__verb,'to go',lang__en,25) },
    { name:(word_class__verb,'salir',lang__es,26) },
    { name:(word_class__verb,'partir',lang__fr,26) },
    { name:(word_class__verb,'to leave',lang__en,26) },
    { name:(word_class__verb,'llegar',lang__es,27) },
    { name:(word_class__verb,'ariver',lang__fr,27) },
    { name:(word_class__verb,'to arrive',lang__en,27) },
    { name:(word_class__verb,'entrar',lang__es,28) },
    { name:(word_class__verb,'entrer',lang__fr,28) },
    { name:(word_class__verb,'to enter',lang__en,28) },
    { name:(word_class__verb,'venir',lang__es,29) },
    { name:(word_class__verb,'venir',lang__fr,29) },
    { name:(word_class__verb,'to come',lang__en,29) },
    { name:(word_class__verb,'viajar',lang__es,30) },
    { name:(word_class__verb,'voyager',lang__fr,30) },
    { name:(word_class__verb,'to travel',lang__en,30) },
    { name:(word_class__verb,'visitar',lang__es,31) },
    { name:(word_class__verb,'visiter',lang__fr,31) },
    { name:(word_class__verb,'to visit',lang__en,31) },
    { name:(word_class__verb,'pasar',lang__es,32) },
    { name:(word_class__verb,'passer',lang__fr,32) },
    { name:(word_class__verb,'to spend',lang__en,32) },
    { name:(word_class__verb,'quedar',lang__es,33) },
    { name:(word_class__verb,'rester',lang__fr,33) },
    { name:(word_class__verb,'to stay',lang__en,33) },
    { name:(word_class__verb,'volver',lang__es,34) },
    { name:(word_class__verb,'retourner',lang__fr,34) },
    { name:(word_class__verb,'to return',lang__en,34) },
    { name:(word_class__verb,'regresar',lang__es,35) },
    { name:(word_class__verb,'reculer',lang__fr,35) },
    { name:(word_class__verb,'to go back',lang__en,35) },
    { name:(word_class__verb,'desaparecer',lang__es,36) },
    { name:(word_class__verb,'disparaître',lang__fr,36) },
    { name:(word_class__verb,'to disappaer',lang__en,36) },
    { name:(word_class__verb,'habitar',lang__es,37) },
    { name:(word_class__verb,'habiter',lang__fr,37) },
    { name:(word_class__verb,'to inhabit',lang__en,37) },
    { name:(word_class__verb,'tener',lang__es,38) },
    { name:(word_class__verb,'avoir',lang__fr,38) },
    { name:(word_class__verb,'to have',lang__en,38) },
    { name:(word_class__verb,'tener que',lang__es,39) },
    { name:(word_class__verb,'devoir',lang__fr,39) },
    { name:(word_class__verb,'to have to',lang__en,39) },
    { name:(word_class__verb,'encontrar',lang__es,40) },
    { name:(word_class__verb,'trouver',lang__fr,40) },
    { name:(word_class__verb,'to find',lang__en,40) },
    { name:(word_class__verb,'mover',lang__es,41) },
    { name:(word_class__verb,'bouger',lang__fr,41) },
    { name:(word_class__verb,'to move',lang__en,41) },
    { name:(word_class__verb,'tomar',lang__es,42) },
    { name:(word_class__verb,'prendre',lang__fr,42) },
    { name:(word_class__verb,'to take',lang__en,42) },
    { name:(word_class__verb,'coger',lang__es,43) },
    { name:(word_class__verb,'llevar',lang__es,44) },
    { name:(word_class__verb,'transporter',lang__fr,44) },
    { name:(word_class__verb,'to carry',lang__en,44) },
    { name:(word_class__verb,'traer',lang__es,45) },
    { name:(word_class__verb,'apporter',lang__fr,45) },
    { name:(word_class__verb,'to bring',lang__en,45) },
    { name:(word_class__verb,'enviar',lang__es,46) },
    { name:(word_class__verb,'mandar',lang__es,47) },
    { name:(word_class__verb,'envoyer',lang__fr,46) },
    { name:(word_class__verb,'envoyer',lang__fr,47) },
    { name:(word_class__verb,'to send',lang__en,46) },
    { name:(word_class__verb,'to send',lang__en,47) },
    { name:(word_class__verb,'cambiar',lang__es,49) },
    { name:(word_class__verb,'changer',lang__fr,49) },
    { name:(word_class__verb,'to change',lang__en,49) },
    { name:(word_class__verb,'abrir',lang__es,50) },
    { name:(word_class__verb,'ouvrir',lang__fr,50) },
    { name:(word_class__verb,'to open',lang__en,50) },
    { name:(word_class__verb,'cerrar',lang__es,51) },
    { name:(word_class__verb,'fermer',lang__fr,51) },
    { name:(word_class__verb,'to close',lang__en,51) },
    { name:(word_class__verb,'apagar',lang__es,52) },
    { name:(word_class__verb,'allumer',lang__fr,52) },
    { name:(word_class__verb,'to turn on',lang__en,52) },
    { name:(word_class__verb,'encender',lang__es,53) },
    { name:(word_class__verb,'fermer',lang__fr,53) },
    { name:(word_class__verb,'to turn off',lang__en,53) },
    { name:(word_class__verb,'romper',lang__es,54) },
    { name:(word_class__verb,'briser',lang__fr,54) },
    { name:(word_class__verb,'to break',lang__en,54) },
    { name:(word_class__verb,'completar',lang__es,55) },
    { name:(word_class__verb,'compléter',lang__fr,55) },
    { name:(word_class__verb,'to complete',lang__en,55) },
    { name:(word_class__verb,'preparar',lang__es,56) },
    { name:(word_class__verb,'préparer',lang__fr,56) },
    { name:(word_class__verb,'to prepare',lang__en,56) },
    { name:(word_class__verb,'abalanzar',lang__es,57) },
    { name:(word_class__verb,'équilibrer',lang__fr,57) },
    { name:(word_class__verb,'to balance',lang__en,57) },
    { name:(word_class__verb,'abandonar',lang__es,58) },
    { name:(word_class__verb,'abandonner',lang__fr,58) },
    { name:(word_class__verb,'to abandon',lang__en,58) },
    { name:(word_class__verb,'abaratar',lang__es,59) },
    { name:(word_class__verb,'dévaloriser',lang__fr,59) },
    { name:(word_class__verb,'to cheapen',lang__en,59) },
    { name:(word_class__verb,'abarcar',lang__es,60) },
    { name:(word_class__verb,'accepter',lang__fr,60) },
    { name:(word_class__verb,'to accept',lang__en,60) },
    { name:(word_class__verb,'elegir',lang__es,61) },
    { name:(word_class__verb,'choisir',lang__fr,61) },
    { name:(word_class__verb,'to chosse',lang__en,61) },
    { name:(word_class__verb,'planear',lang__es,62) },
    { name:(word_class__verb,'planifier',lang__fr,62) },
    { name:(word_class__verb,'to plan',lang__en,62) },
    { name:(word_class__verb,'hacer',lang__es,63) },
    { name:(word_class__verb,'faire',lang__fr,63) },
    { name:(word_class__verb,'to do',lang__en,63) },
    { name:(word_class__verb,'probar',lang__es,64) },
    { name:(word_class__verb,'essayer',lang__fr,64) },
    { name:(word_class__verb,'to try',lang__en,64) },
    { name:(word_class__verb,'intentar',lang__es,65) },
    { name:(word_class__verb,'essayer',lang__fr,65) },
    { name:(word_class__verb,'to try',lang__en,65) },
    { name:(word_class__verb,'practicar',lang__es,66) },
    { name:(word_class__verb,'pratiquer',lang__fr,66) },
    { name:(word_class__verb,'to practice',lang__en,66) },
    { name:(word_class__verb,'empezar',lang__es,67) },
    { name:(word_class__verb,'commencer',lang__fr,67) },
    { name:(word_class__verb,'to start',lang__en,67) },
    { name:(word_class__verb,'comenzar',lang__es,68) },
    { name:(word_class__verb,'commencer',lang__fr,68) },
    { name:(word_class__verb,'to begin',lang__en,68) },
    { name:(word_class__verb,'seguir',lang__es,69) },
    { name:(word_class__verb,'continuer',lang__fr,69) },
    { name:(word_class__verb,'to continue',lang__en,69) },
    { name:(word_class__verb,'parar',lang__es,70) },
    { name:(word_class__verb,'arrêter',lang__fr,70) },
    { name:(word_class__verb,'to stop',lang__en,70) },
    { name:(word_class__verb,'esperar',lang__es,71) },
    { name:(word_class__verb,'attendre',lang__fr,71) },
    { name:(word_class__verb,'to wait',lang__en,71) },
    { name:(word_class__verb,'acabar',lang__es,72) },
    { name:(word_class__verb,'finir',lang__fr,72) },
    { name:(word_class__verb,'to finish',lang__en,72) },
    { name:(word_class__verb,'repetir',lang__es,73) },
    { name:(word_class__verb,'répéter',lang__fr,73) },
    { name:(word_class__verb,'to repeat',lang__en,73) },
    { name:(word_class__verb,'ocurrir',lang__es,74) },
    { name:(word_class__verb,'se produire',lang__fr,74) },
    { name:(word_class__verb,'to occur',lang__en,74) },
    { name:(word_class__verb,'morir',lang__es,75) },
    { name:(word_class__verb,'mourir',lang__fr,75) },
    { name:(word_class__verb,'to die',lang__en,75) },
    { name:(word_class__verb,'sentir',lang__fr,94) },
    { name:(word_class__verb,'to feel',lang__en,94) },
    { name:(word_class__verb,'sentirse',lang__es,94) },
    { name:(word_class__verb,'être plu par',lang__fr,95) },
    { name:(word_class__verb,'to enjoy',lang__en,95) },
    { name:(word_class__verb,'gustar',lang__es,95) },
    { name:(word_class__verb,'pleurer',lang__fr,96) },
    { name:(word_class__verb,'to cry',lang__en,96) },
    { name:(word_class__verb,'llorar',lang__es,96) },
    { name:(word_class__verb,'mourir',lang__fr,97) },
    { name:(word_class__verb,'to die',lang__en,97) },
    { name:(word_class__verb,'morir',lang__es,97) },
    { name:(word_class__verb,'se reposer',lang__fr,98) },
    { name:(word_class__verb,'to rest',lang__en,98) },
    { name:(word_class__verb,'descansar',lang__es,98) },
    { name:(word_class__verb,'dormir',lang__fr,99) },
    { name:(word_class__verb,'to sleep',lang__en,99) },
    { name:(word_class__verb,'dormir',lang__es,99) },
    { name:(word_class__verb,'se coucher',lang__fr,100) },
    { name:(word_class__verb,'to go to bed',lang__en,100) },
    { name:(word_class__verb,'acostar',lang__es,100) },
    { name:(word_class__verb,'rêver',lang__fr,101) },
    { name:(word_class__verb,'to dream',lang__en,101) },
    { name:(word_class__verb,'soñar',lang__es,101) },
    { name:(word_class__verb,'ronfler',lang__fr,102) },
    { name:(word_class__verb,'to snore',lang__en,102) },
    { name:(word_class__verb,'roncar',lang__es,102) },
    { name:(word_class__verb,'se réveiller',lang__fr,103) },
    { name:(word_class__verb,'to wake up',lang__en,103) },
    { name:(word_class__verb,'despetar',lang__es,103) },
    { name:(word_class__verb,'avoir mal',lang__fr,104) },
    { name:(word_class__verb,'to hurt',lang__en,104) },
    { name:(word_class__verb,'doler',lang__es,104) },
    { name:(word_class__verb,'regarder',lang__fr,105) },
    { name:(word_class__verb,'to see',lang__en,105) },
    { name:(word_class__verb,'mirar',lang__es,105) },
    { name:(word_class__verb,'regarder',lang__fr,106) },
    { name:(word_class__verb,'to watch',lang__en,106) },
    { name:(word_class__verb,'ver',lang__es,106) },
    { name:(word_class__verb,'entendre',lang__fr,107) },
    { name:(word_class__verb,'to hear',lang__en,107) },
    { name:(word_class__verb,'oír',lang__es,107) },
    { name:(word_class__verb,'écouter',lang__fr,108) },
    { name:(word_class__verb,'to listen',lang__en,108) },
    { name:(word_class__verb,'escuchar',lang__es,108) },
    { name:(word_class__verb,'boire',lang__fr,109) },
    { name:(word_class__verb,'to drink',lang__en,109) },
    { name:(word_class__verb,'beber',lang__es,109) },
    { name:(word_class__verb,'manger',lang__fr,110) },
    { name:(word_class__verb,'to eat',lang__en,110) },
    { name:(word_class__verb,'comer',lang__es,110) },
    { name:(word_class__verb,'aller dîner',lang__fr,111) },
    { name:(word_class__verb,'to have lunch',lang__en,111) },
    { name:(word_class__verb,'almorzar',lang__es,111) },
    { name:(word_class__verb,'souper',lang__fr,112) },
    { name:(word_class__verb,'to have dinner',lang__en,112) },
    { name:(word_class__verb,'cenar',lang__es,112) },
    { name:(word_class__verb,'déjeûner',lang__fr,113) },
    { name:(word_class__verb,'to have breakfast',lang__en,113) },
    { name:(word_class__verb,'desayunar',lang__es,113) },
    { name:(word_class__verb,'se vêtir',lang__fr,114) },
    { name:(word_class__verb,'to dress oneself',lang__en,114) },
    { name:(word_class__verb,'vestir',lang__es,114) },
    { name:(word_class__verb,'aimer',lang__fr,115) },
    { name:(word_class__verb,'to love',lang__en,115) },
    { name:(word_class__verb,'amar',lang__es,115) },
    { name:(word_class__verb,'apprécier',lang__fr,116) },
    { name:(word_class__verb,'to enjoy',lang__en,116) },
    { name:(word_class__verb,'disfrutar',lang__es,116) },
    { name:(word_class__verb,'préférer',lang__fr,117) },
    { name:(word_class__verb,'to prefer',lang__en,117) },
    { name:(word_class__verb,'preferir',lang__es,117) },
    { name:(word_class__verb,'se préoccuper',lang__fr,118) },
    { name:(word_class__verb,'to worry',lang__en,118) },
    { name:(word_class__verb,'preocupar',lang__es,118) },
    { name:(word_class__verb,'haïr',lang__fr,119) },
    { name:(word_class__verb,'to hate',lang__en,119) },
    { name:(word_class__verb,'odiar',lang__es,119) },
    { name:(word_class__verb,'s\'ennuyer',lang__fr,120) },
    { name:(word_class__verb,'to miss',lang__en,120) },
    { name:(word_class__verb,'extrañar',lang__es,120) },
    { name:(word_class__verb,'penser',lang__fr,121) },
    { name:(word_class__verb,'to think',lang__en,121) },
    { name:(word_class__verb,'pensar',lang__es,121) },
    { name:(word_class__verb,'croire',lang__fr,122) },
    { name:(word_class__verb,'to believe',lang__en,122) },
    { name:(word_class__verb,'crer',lang__es,122) },
    { name:(word_class__verb,'décider',lang__fr,123) },
    { name:(word_class__verb,'to decide',lang__en,123) },
    { name:(word_class__verb,'decidir',lang__es,123) },
    { name:(word_class__verb,'s\'intéresser',lang__fr,124) },
    { name:(word_class__verb,'to be interested in',lang__en,124) },
    { name:(word_class__verb,'interesar',lang__es,124) },
    { name:(word_class__verb,'apprendre',lang__fr,125) },
    { name:(word_class__verb,'to learn',lang__en,125) },
    { name:(word_class__verb,'aprendar',lang__es,125) },
    { name:(word_class__verb,'étudier',lang__fr,126) },
    { name:(word_class__verb,'to study',lang__en,126) },
    { name:(word_class__verb,'estudiar',lang__es,126) },
    { name:(word_class__verb,'enseigner',lang__fr,127) },
    { name:(word_class__verb,'to teach',lang__en,127) },
    { name:(word_class__verb,'enseñar',lang__es,127) },
    { name:(word_class__verb,'se rappeller',lang__fr,128) },
    { name:(word_class__verb,'to remember',lang__en,128) },
    { name:(word_class__verb,'recordar',lang__es,128) },
    { name:(word_class__verb,'comprendre',lang__fr,129) },
    { name:(word_class__verb,'to understand',lang__en,129) },
    { name:(word_class__verb,'entender',lang__es,129) },
    { name:(word_class__verb,'comprendre',lang__fr,130) },
    { name:(word_class__verb,'to understand',lang__en,130) },
    { name:(word_class__verb,'comprender',lang__es,130) },
    { name:(word_class__verb,'oublier',lang__fr,131) },
    { name:(word_class__verb,'to forget',lang__en,131) },
    { name:(word_class__verb,'olvidar',lang__es,131) },
    { name:(word_class__verb,'avoir besoin de',lang__fr,132) },
    { name:(word_class__verb,'to need',lang__en,132) },
    { name:(word_class__verb,'necesitar',lang__es,132) },
    { name:(word_class__verb,'chercher',lang__fr,133) },
    { name:(word_class__verb,'to look for',lang__en,133) },
    { name:(word_class__verb,'buscar',lang__es,133) },
    { name:(word_class__verb,'demander',lang__fr,134) },
    { name:(word_class__verb,'to order',lang__en,134) },
    { name:(word_class__verb,'pedir',lang__es,134) },
    { name:(word_class__verb,'servir',lang__fr,135) },
    { name:(word_class__verb,'to serve',lang__en,135) },
    { name:(word_class__verb,'servir',lang__es,135) },
    { name:(word_class__verb,'fournir',lang__fr,136) },
    { name:(word_class__verb,'to supply',lang__en,136) },
    { name:(word_class__verb,'abastecer',lang__es,136) },
    { name:(word_class__verb,'prendre une douche',lang__fr,137) },
    { name:(word_class__verb,'to shower',lang__en,137) },
    { name:(word_class__verb,'duchar',lang__es,137) },
    { name:(word_class__verb,'laver',lang__fr,138) },
    { name:(word_class__verb,'to wash',lang__en,138) },
    { name:(word_class__verb,'lavar',lang__es,138) },
    { name:(word_class__verb,'laver',lang__fr,139) },
    { name:(word_class__verb,'to clean',lang__en,139) },
    { name:(word_class__verb,'limpiar',lang__es,139) },
    { name:(word_class__verb,'s\'occuper de',lang__fr,140) },
    { name:(word_class__verb,'to take care of',lang__en,140) },
    { name:(word_class__verb,'cuidar',lang__es,140) },
    { name:(word_class__verb,'brosser',lang__fr,141) },
    { name:(word_class__verb,'to brush',lang__en,141) },
    { name:(word_class__verb,'cepillar',lang__es,141) },
    { name:(word_class__verb,'réparer',lang__fr,142) },
    { name:(word_class__verb,'to repair',lang__en,142) },
    { name:(word_class__verb,'reparar',lang__es,142) },
    { name:(word_class__verb,'porter',lang__fr,143) },
    { name:(word_class__verb,'to wear',lang__en,143) },
    { name:(word_class__verb,'usar',lang__es,143) },
    { name:(word_class__verb,'utiliser',lang__fr,144) },
    { name:(word_class__verb,'to use',lang__en,144) },
    { name:(word_class__verb,'usar',lang__es,144) },
    { name:(word_class__verb,'mettre',lang__fr,145) },
    { name:(word_class__verb,'to put on',lang__en,145) },
    { name:(word_class__verb,'poner',lang__es,145) },
    { name:(word_class__verb,'parler',lang__fr,146) },
    { name:(word_class__verb,'to speak',lang__en,146) },
    { name:(word_class__verb,'hablar',lang__es,146) },
    { name:(word_class__verb,'lire',lang__fr,147) },
    { name:(word_class__verb,'to read',lang__en,147) },
    { name:(word_class__verb,'leer',lang__es,147) },
    { name:(word_class__verb,'jouer',lang__fr,148) },
    { name:(word_class__verb,'to play',lang__en,148) },
    { name:(word_class__verb,'tocar',lang__es,148) },
    { name:(word_class__verb,'fumer',lang__fr,149) },
    { name:(word_class__verb,'to smoke',lang__en,149) },
    { name:(word_class__verb,'fumar',lang__es,149) },
    { name:(word_class__verb,'conduire',lang__fr,150) },
    { name:(word_class__verb,'to drive',lang__en,150) },
    { name:(word_class__verb,'manejar',lang__es,150) },
    { name:(word_class__verb,'monter',lang__fr,151) },
    { name:(word_class__verb,'to ride',lang__en,151) },
    { name:(word_class__verb,'montar',lang__es,151) },
    { name:(word_class__verb,'ventiler',lang__fr,152) },
    { name:(word_class__verb,'to fan',lang__en,152) },
    { name:(word_class__verb,'abanicar',lang__es,152) },
    { name:(word_class__verb,'donner',lang__fr,153) },
    { name:(word_class__verb,'to give',lang__en,153) },
    { name:(word_class__verb,'dar',lang__es,153) },
    { name:(word_class__verb,'recevoir',lang__fr,154) },
    { name:(word_class__verb,'to receive',lang__en,154) },
    { name:(word_class__verb,'recivir',lang__es,154) },
    { name:(word_class__verb,'payer',lang__fr,155) },
    { name:(word_class__verb,'to pay',lang__en,155) },
    { name:(word_class__verb,'pagar',lang__es,155) },
    { name:(word_class__verb,'acheter',lang__fr,156) },
    { name:(word_class__verb,'to buy',lang__en,156) },
    { name:(word_class__verb,'comprar',lang__es,156) },
    { name:(word_class__verb,'réserver',lang__fr,157) },
    { name:(word_class__verb,'to reserve',lang__en,157) },
    { name:(word_class__verb,'reservar',lang__es,157) },
    { name:(word_class__verb,'pêcher',lang__fr,158) },
    { name:(word_class__verb,'to fish',lang__en,158) },
    { name:(word_class__verb,'pescar',lang__es,158) },
    { name:(word_class__verb,'inviter',lang__fr,159) },
    { name:(word_class__verb,'to invite',lang__en,159) },
    { name:(word_class__verb,'invitar',lang__es,159) },
    { name:(word_class__verb,'connaître',lang__fr,160) },
    { name:(word_class__verb,'to know',lang__en,160) },
    { name:(word_class__verb,'conocer',lang__es,160) },
    { name:(word_class__verb,'rencontrer',lang__fr,161) },
    { name:(word_class__verb,'to meet',lang__en,161) },
    { name:(word_class__verb,'encontrar',lang__es,161) },
    { name:(word_class__verb,'rejoindre',lang__fr,162) },
    { name:(word_class__verb,'to meet up',lang__en,162) },
    { name:(word_class__verb,'quedar',lang__es,162) },
    { name:(word_class__verb,'accompagner',lang__fr,163) },
    { name:(word_class__verb,'to go along with',lang__en,163) },
    { name:(word_class__verb,'acompañar',lang__es,163) },
    { name:(word_class__verb,'demander',lang__fr,164) },
    { name:(word_class__verb,'to ask',lang__en,164) },
    { name:(word_class__verb,'preguntar',lang__es,164) },
    { name:(word_class__verb,'répondre',lang__fr,165) },
    { name:(word_class__verb,'to answer',lang__en,165) },
    { name:(word_class__verb,'responder',lang__es,165) },
    { name:(word_class__verb,'dire',lang__fr,166) },
    { name:(word_class__verb,'to tell',lang__en,166) },
    { name:(word_class__verb,'decir',lang__es,166) },
    { name:(word_class__verb,'appeller',lang__fr,167) },
    { name:(word_class__verb,'to call',lang__en,167) },
    { name:(word_class__verb,'llamar',lang__es,167) },
    { name:(word_class__verb,'avoir une conversation',lang__fr,168) },
    { name:(word_class__verb,'to chat',lang__en,168) },
    { name:(word_class__verb,'conversar',lang__es,168) },
    { name:(word_class__verb,'arrimer',lang__fr,169) },
    { name:(word_class__verb,'to stow',lang__en,169) },
    { name:(word_class__verb,'abarrotar',lang__es,169) },
    { name:(word_class__verb,'écrire',lang__fr,170) },
    { name:(word_class__verb,'to write',lang__en,170) },
    { name:(word_class__verb,'escribir',lang__es,170) },
    { name:(word_class__verb,'cuisiner',lang__fr,171) },
    { name:(word_class__verb,'to cook',lang__en,171) },
    { name:(word_class__verb,'cocinar',lang__es,171) },
    { name:(word_class__verb,'dessiner',lang__fr,172) },
    { name:(word_class__verb,'to draw',lang__en,172) },
    { name:(word_class__verb,'dibujar',lang__es,172) },
    { name:(word_class__verb,'peinturer',lang__fr,173) },
    { name:(word_class__verb,'to paint',lang__en,173) },
    { name:(word_class__verb,'pintar',lang__es,173) },
    { name:(word_class__verb,'chanter',lang__fr,174) },
    { name:(word_class__verb,'to sing',lang__en,174) },
    { name:(word_class__verb,'cantar',lang__es,174) },
    { name:(word_class__verb,'travailler',lang__fr,175) },
    { name:(word_class__verb,'to work',lang__en,175) },
    { name:(word_class__verb,'trabajar',lang__es,175) },
    { name:(word_class__verb,'jouer',lang__fr,176) },
    { name:(word_class__verb,'to play',lang__en,176) },
    { name:(word_class__verb,'jugar',lang__es,176) },
    { name:(word_class__verb,'passer',lang__fr,177) },
    { name:(word_class__verb,'to pass',lang__en,177) },
    { name:(word_class__verb,'aprobar',lang__es,177) },
    { name:(word_class__verb,'gagner',lang__fr,178) },
    { name:(word_class__verb,'to win',lang__en,178) },
    { name:(word_class__verb,'ganar',lang__es,178) },
    { name:(word_class__verb,'perdre',lang__fr,179) },
    { name:(word_class__verb,'to lose',lang__en,179) },
    { name:(word_class__verb,'perder',lang__es,179) },
    { name:(word_class__verb,'prier',lang__fr,180) },
    { name:(word_class__verb,'to pray',lang__en,180) },
    { name:(word_class__verb,'rezar',lang__es,180) },
    { name:(word_class__verb,'empoisonner',lang__fr,181) },
    { name:(word_class__verb,'to poison',lang__en,181) },
    { name:(word_class__verb,'envenenar',lang__es,181) },
    { name:(word_class__noun,'mot ',lang__fr,182) },
    { name:(word_class__noun,'word',lang__en,182) },
    { name:(word_class__noun,'palabra',lang__es,182) },
    { name:(word_class__adverb,'où',lang__fr,183) },
    { name:(word_class__adverb,'where',lang__en,183) },
    { name:(word_class__adverb,'dónde',lang__es,183) },
    { name:(word_class__adverb,'quand',lang__fr,184) },
    { name:(word_class__adverb,'when',lang__en,184) },
    { name:(word_class__adverb,'cuándo',lang__es,184) },
    { name:(word_class__adverb,'qu\'est-ce',lang__fr,185) },
    { name:(word_class__adverb,'what',lang__en,185) },
    { name:(word_class__adverb,'qué',lang__es,185) },
    { name:(word_class__adverb,'qui',lang__fr,186) },
    { name:(word_class__adverb,'who',lang__en,186) },
    { name:(word_class__adverb,'quién',lang__es,186) },
    { name:(word_class__adverb,'pourquoi',lang__fr,187) },
    { name:(word_class__adverb,'why',lang__en,187) },
    { name:(word_class__adverb,'por qué',lang__es,187) },
    { name:(word_class__adverb,'lequel',lang__fr,188) },
    { name:(word_class__adverb,'which',lang__en,188) },
    { name:(word_class__adverb,'cuál',lang__es,188) },
    { name:(word_class__adverb,'combien',lang__fr,189) },
    { name:(word_class__adverb,'how much',lang__en,189) },
    { name:(word_class__adverb,'cuánto',lang__es,189) },
    { name:(word_class__adverb,'combien',lang__fr,190) },
    { name:(word_class__adverb,'how many',lang__en,190) },
    { name:(word_class__adverb,'cuántas',lang__es,190) },
    { name:(word_class__adverb,'comment',lang__fr,191) },
    { name:(word_class__adverb,'how',lang__en,191) },
    { name:(word_class__adverb,'cómo',lang__es,191) },
    { name:(word_class__adverb,'ici',lang__fr,192) },
    { name:(word_class__adverb,'here',lang__en,192) },
    { name:(word_class__adverb,'aqui',lang__es,192) },
    { name:(word_class__adverb,'proche',lang__fr,193) },
    { name:(word_class__adverb,'nearby',lang__en,193) },
    { name:(word_class__adverb,'acá',lang__es,193) },
    { name:(word_class__adverb,'par là',lang__fr,194) },
    { name:(word_class__adverb,'over there',lang__en,194) },
    { name:(word_class__adverb,'allá',lang__es,194) },
    { name:(word_class__adverb,'là',lang__fr,195) },
    { name:(word_class__adverb,'there',lang__en,195) },
    { name:(word_class__adverb,'allí',lang__es,195) },
    { name:(word_class__adverb,'là-bas',lang__fr,196) },
    { name:(word_class__adverb,'there',lang__en,196) },
    { name:(word_class__adverb,'ahí',lang__es,196) },
    { name:(word_class__adverb,'partout',lang__fr,197) },
    { name:(word_class__adverb,'everywhere',lang__en,197) },
    { name:(word_class__adverb,'en todas partes',lang__es,197) },
    { name:(word_class__adverb,'proche',lang__fr,198) },
    { name:(word_class__adverb,'near',lang__en,198) },
    { name:(word_class__adverb,'cerca',lang__es,198) },
    { name:(word_class__adverb,'à côté de',lang__fr,199) },
    { name:(word_class__adverb,'next to',lang__en,199) },
    { name:(word_class__adverb,'al lado',lang__es,199) },
    { name:(word_class__adverb,'loin',lang__fr,200) },
    { name:(word_class__adverb,'far',lang__en,200) },
    { name:(word_class__adverb,'lejos',lang__es,200) },
    { name:(word_class__adverb,'à l\'intérieur',lang__fr,201) },
    { name:(word_class__adverb,'inside',lang__en,201) },
    { name:(word_class__adverb,'adentro',lang__es,201) },
    { name:(word_class__adverb,'par dessus',lang__fr,202) },
    { name:(word_class__adverb,'on (top of)',lang__en,202) },
    { name:(word_class__adverb,'sobre',lang__es,202) },
    { name:(word_class__adverb,'par dessus',lang__fr,203) },
    { name:(word_class__adverb,'on top of',lang__en,203) },
    { name:(word_class__adverb,'encíma',lang__es,203) },
    { name:(word_class__adverb,'sous',lang__fr,204) },
    { name:(word_class__adverb,'under',lang__en,204) },
    { name:(word_class__adverb,'debajo',lang__es,204) },
    { name:(word_class__adverb,'derrière',lang__fr,205) },
    { name:(word_class__adverb,'behind',lang__en,205) },
    { name:(word_class__adverb,'detrás',lang__es,205) },
    { name:(word_class__adverb,'en avant',lang__fr,206) },
    { name:(word_class__adverb,'in front of',lang__en,206) },
    { name:(word_class__adverb,'enfrente',lang__es,206) },
    { name:(word_class__adverb,'entre',lang__fr,207) },
    { name:(word_class__adverb,'between',lang__en,207) },
    { name:(word_class__adverb,'entre',lang__es,207) },
    { name:(word_class__adverb,'dans',lang__fr,208) },
    { name:(word_class__adverb,'inside',lang__en,208) },
    { name:(word_class__adverb,'dentro',lang__es,208) },
    { name:(word_class__adverb,'en bas',lang__fr,209) },
    { name:(word_class__adverb,'downstairs',lang__en,209) },
    { name:(word_class__adverb,'abajo',lang__es,209) },
    { name:(word_class__adverb,'en haut',lang__fr,210) },
    { name:(word_class__adverb,'upstairs',lang__en,210) },
    { name:(word_class__adverb,'arriba',lang__es,210) },
    { name:(word_class__adverb,'en arrière',lang__fr,211) },
    { name:(word_class__adverb,'in the back',lang__en,211) },
    { name:(word_class__adverb,'atrás',lang__es,211) },
    { name:(word_class__adverb,'dehors',lang__fr,212) },
    { name:(word_class__adverb,'outside',lang__en,212) },
    { name:(word_class__adverb,'fuera',lang__es,212) },
    { name:(word_class__adverb,'à travers',lang__fr,213) },
    { name:(word_class__adverb,'through',lang__en,213) },
    { name:(word_class__adverb,'por',lang__es,213) },
    { name:(word_class__adverb,'le long de',lang__fr,214) },
    { name:(word_class__adverb,'along',lang__en,214) },
    { name:(word_class__adverb,'por',lang__es,214) },
    { name:(word_class__adverb,'vers',lang__fr,215) },
    { name:(word_class__adverb,'around',lang__en,215) },
    { name:(word_class__adverb,'por',lang__es,215) },
    { name:(word_class__adverb,'par ici',lang__fr,216) },
    { name:(word_class__adverb,'this way',lang__en,216) },
    { name:(word_class__adverb,'por aquí',lang__es,216) },
    { name:(word_class__adverb,'très',lang__fr,217) },
    { name:(word_class__adverb,'very',lang__en,217) },
    { name:(word_class__adverb,'muy',lang__es,217) },
    { name:(word_class__adverb,'plus',lang__fr,218) },
    { name:(word_class__adverb,'more',lang__en,218) },
    { name:(word_class__adverb,'más',lang__es,218) },
    { name:(word_class__adverb,'extra',lang__fr,219) },
    { name:(word_class__adverb,'extra',lang__en,219) },
    { name:(word_class__adverb,'extra',lang__es,219) },
    { name:(word_class__adverb,'trop',lang__fr,220) },
    { name:(word_class__adverb,'too/too much/too many',lang__en,220) },
    { name:(word_class__adverb,'demasiado',lang__es,220) },
    { name:(word_class__adverb,'beaucoup',lang__fr,221) },
    { name:(word_class__adverb,'a lot',lang__en,221) },
    { name:(word_class__adverb,'mucho',lang__es,221) },
    { name:(word_class__adverb,'peu',lang__fr,222) },
    { name:(word_class__adverb,'few',lang__en,222) },
    { name:(word_class__adverb,'poco',lang__es,222) },
    { name:(word_class__adverb,'plusieurs',lang__fr,223) },
    { name:(word_class__adverb,'many',lang__en,223) },
    { name:(word_class__adverb,'varios',lang__es,223) },
    { name:(word_class__adverb,'quelques',lang__fr,224) },
    { name:(word_class__adverb,'some',lang__en,224) },
    { name:(word_class__adverb,'unas',lang__es,224) },
    { name:(word_class__adverb,'les deux',lang__fr,225) },
    { name:(word_class__adverb,'both',lang__en,225) },
    { name:(word_class__adverb,'ambas',lang__es,225) },
    { name:(word_class__adverb,'complètement',lang__fr,226) },
    { name:(word_class__adverb,'completely',lang__en,226) },
    { name:(word_class__adverb,'completamente',lang__es,226) },
    { name:(word_class__adverb,'aucun',lang__fr,227) },
    { name:(word_class__adverb,'none',lang__en,227) },
    { name:(word_class__adverb,'ninguno',lang__es,227) },
    { name:(word_class__adverb,'quelque',lang__fr,228) },
    { name:(word_class__adverb,'some',lang__en,228) },
    { name:(word_class__adverb,'algún',lang__es,228) },
    { name:(word_class__adverb,'quelques',lang__fr,229) },
    { name:(word_class__adverb,'some',lang__en,229) },
    { name:(word_class__adverb,'algunos',lang__es,229) },
    { name:(word_class__adverb,'presque',lang__fr,230) },
    { name:(word_class__adverb,'almost',lang__en,230) },
    { name:(word_class__adverb,'casi',lang__es,230) },
    { name:(word_class__adverb,'maintenant',lang__fr,231) },
    { name:(word_class__adverb,'now',lang__en,231) },
    { name:(word_class__adverb,'ahora',lang__es,231) },
    { name:(word_class__adverb,'une autre fois',lang__fr,232) },
    { name:(word_class__adverb,'another time',lang__en,232) },
    { name:(word_class__adverb,'otra vez',lang__es,232) },
    { name:(word_class__adverb,'cette fois-ci',lang__fr,233) },
    { name:(word_class__adverb,'this time',lang__en,233) },
    { name:(word_class__adverb,'esta vez',lang__es,233) },
    { name:(word_class__adverb,'en ce moment même',lang__fr,234) },
    { name:(word_class__adverb,'right now',lang__en,234) },
    { name:(word_class__adverb,'ahora mismo',lang__es,234) },
    { name:(word_class__adverb,'un jour',lang__fr,235) },
    { name:(word_class__adverb,'someday',lang__en,235) },
    { name:(word_class__adverb,'algun día',lang__es,235) },
    { name:(word_class__adverb,'tout le temps',lang__fr,236) },
    { name:(word_class__adverb,'all the time',lang__en,236) },
    { name:(word_class__adverb,'todo el tiempo',lang__es,236) },
    { name:(word_class__adverb,'il y a longtemps',lang__fr,237) },
    { name:(word_class__adverb,'a long time ago',lang__en,237) },
    { name:(word_class__adverb,'hace mucho tiempo',lang__es,237) },
    { name:(word_class__adverb,'puis',lang__fr,238) },
    { name:(word_class__adverb,'then',lang__en,238) },
    { name:(word_class__adverb,'entonces',lang__es,238) },
    { name:(word_class__adverb,'avant',lang__fr,239) },
    { name:(word_class__adverb,'before',lang__en,239) },
    { name:(word_class__adverb,'antes',lang__es,239) },
    { name:(word_class__adverb,'après',lang__fr,240) },
    { name:(word_class__adverb,'after',lang__en,240) },
    { name:(word_class__adverb,'después',lang__es,240) },
    { name:(word_class__adverb,'autour de',lang__fr,241) },
    { name:(word_class__adverb,'around',lang__en,241) },
    { name:(word_class__adverb,'sobre',lang__es,241) },
    { name:(word_class__adverb,'pour',lang__fr,242) },
    { name:(word_class__adverb,'for',lang__en,242) },
    { name:(word_class__adverb,'para',lang__es,242) },
    { name:(word_class__adverb,'plus',lang__fr,243) },
    { name:(word_class__adverb,'no more',lang__en,243) },
    { name:(word_class__adverb,'más',lang__es,243) },
    { name:(word_class__adverb,'qui vient',lang__fr,244) },
    { name:(word_class__adverb,'next',lang__en,244) },
    { name:(word_class__adverb,'que viene',lang__es,244) },
    { name:(word_class__adverb,'prochain',lang__fr,245) },
    { name:(word_class__adverb,'next',lang__en,245) },
    { name:(word_class__adverb,'siguiente',lang__es,245) },
    { name:(word_class__adverb,'plus tard',lang__fr,246) },
    { name:(word_class__adverb,'later',lang__en,246) },
    { name:(word_class__adverb,'luego',lang__es,246) },
    { name:(word_class__adverb,'passé',lang__fr,247) },
    { name:(word_class__adverb,'last',lang__en,247) },
    { name:(word_class__adverb,'pasada',lang__es,247) },
    { name:(word_class__adverb,'premier',lang__fr,248) },
    { name:(word_class__adverb,'first',lang__en,248) },
    { name:(word_class__adverb,'primero',lang__es,248) },
    { name:(word_class__adverb,'tôt',lang__fr,249) },
    { name:(word_class__adverb,'early',lang__en,249) },
    { name:(word_class__adverb,'temprano',lang__es,249) },
    { name:(word_class__adverb,'tard',lang__fr,250) },
    { name:(word_class__adverb,'late',lang__en,250) },
    { name:(word_class__adverb,'tarde',lang__es,250) },
    { name:(word_class__adverb,'bientôt',lang__fr,251) },
    { name:(word_class__adverb,'soon',lang__en,251) },
    { name:(word_class__adverb,'pronto',lang__es,251) },
    { name:(word_class__adverb,'il y a',lang__fr,252) },
    { name:(word_class__adverb,'ago',lang__en,252) },
    { name:(word_class__adverb,'hace',lang__es,252) },
    { name:(word_class__adverb,'finalement',lang__fr,253) },
    { name:(word_class__adverb,'finally',lang__en,253) },
    { name:(word_class__adverb,'por fin',lang__es,253) },
    { name:(word_class__adverb,'jamais',lang__fr,254) },
    { name:(word_class__adverb,'never',lang__en,254) },
    { name:(word_class__adverb,'nunca',lang__es,254) },
    { name:(word_class__adverb,'jamais',lang__fr,255) },
    { name:(word_class__adverb,'never',lang__en,255) },
    { name:(word_class__adverb,'jamás',lang__es,255) },
    { name:(word_class__adverb,'desfois',lang__fr,256) },
    { name:(word_class__adverb,'sometimes',lang__en,256) },
    { name:(word_class__adverb,'a veces',lang__es,256) },
    { name:(word_class__adverb,'de temps en temps',lang__fr,257) },
    { name:(word_class__adverb,'once in a while',lang__en,257) },
    { name:(word_class__adverb,'de vez en cuando',lang__es,257) },
    { name:(word_class__adverb,'normalement',lang__fr,258) },
    { name:(word_class__adverb,'normally',lang__en,258) },
    { name:(word_class__adverb,'normalemente',lang__es,258) },
    { name:(word_class__adverb,'d\'habitude',lang__fr,259) },
    { name:(word_class__adverb,'usually',lang__en,259) },
    { name:(word_class__adverb,'usualmente',lang__es,259) },
    { name:(word_class__adverb,'généralement',lang__fr,260) },
    { name:(word_class__adverb,'generally',lang__en,260) },
    { name:(word_class__adverb,'generalmente',lang__es,260) },
    { name:(word_class__adverb,'fréquemment',lang__fr,261) },
    { name:(word_class__adverb,'frequently',lang__en,261) },
    { name:(word_class__adverb,'frecuentemente',lang__es,261) },
    { name:(word_class__adverb,'souvent',lang__fr,262) },
    { name:(word_class__adverb,'often',lang__en,262) },
    { name:(word_class__adverb,'a menudo',lang__es,262) },
    { name:(word_class__adverb,'toujours',lang__fr,263) },
    { name:(word_class__adverb,'always',lang__en,263) },
    { name:(word_class__adverb,'siempre',lang__es,263) },
    { name:(word_class__preposition,'à',lang__fr,264) },
    { name:(word_class__preposition,'to',lang__en,264) },
    { name:(word_class__preposition,'a',lang__es,264) },
    { name:(word_class__preposition,'à',lang__fr,265) },
    { name:(word_class__preposition,'in',lang__en,265) },
    { name:(word_class__preposition,'en',lang__es,265) },
    { name:(word_class__preposition,'pour',lang__fr,266) },
    { name:(word_class__preposition,'for',lang__en,266) },
    { name:(word_class__preposition,'para',lang__es,266) },
    { name:(word_class__preposition,'avec',lang__fr,267) },
    { name:(word_class__preposition,'with',lang__en,267) },
    { name:(word_class__preposition,'con',lang__es,267) },
    { name:(word_class__preposition,'sans',lang__fr,268) },
    { name:(word_class__preposition,'without',lang__en,268) },
    { name:(word_class__preposition,'sin',lang__es,268) },
    { name:(word_class__preposition,'avec toi',lang__fr,269) },
    { name:(word_class__preposition,'with you',lang__en,269) },
    { name:(word_class__preposition,'contigo',lang__es,269) },
    { name:(word_class__preposition,'avec moi',lang__fr,270) },
    { name:(word_class__preposition,'with me',lang__en,270) },
    { name:(word_class__preposition,'conmigo',lang__es,270) },
    { name:(word_class__preposition,'de',lang__fr,271) },
    { name:(word_class__preposition,'from',lang__en,271) },
    { name:(word_class__preposition,'de',lang__es,271) },
    { name:(word_class__preposition,'',lang__fr,272) },
    { name:(word_class__preposition,'on',lang__en,272) },
    { name:(word_class__preposition,'el',lang__es,272) },
    { name:(word_class__preposition,'à',lang__fr,273) },
    { name:(word_class__preposition,'at',lang__en,273) },
    { name:(word_class__preposition,'a las',lang__es,273) },
    { name:(word_class__preposition,'par',lang__fr,274) },
    { name:(word_class__preposition,'by',lang__en,274) },
    { name:(word_class__preposition,'por',lang__es,274) },
    { name:(word_class__preposition,'pendant',lang__fr,275) },
    { name:(word_class__preposition,'during',lang__en,275) },
    { name:(word_class__preposition,'durante',lang__es,275) },
    { name:(word_class__preposition,'jusqu\'à',lang__fr,276) },
    { name:(word_class__preposition,'until',lang__en,276) },
    { name:(word_class__preposition,'hasta',lang__es,276) },
    { name:(word_class__preposition,'après',lang__fr,277) },
    { name:(word_class__preposition,'after',lang__en,277) },
    { name:(word_class__preposition,'tras',lang__es,277) },
    { name:(word_class__preposition,'excepté',lang__fr,278) },
    { name:(word_class__preposition,'except',lang__en,278) },
    { name:(word_class__preposition,'excepto',lang__es,278) },
    { name:(word_class__adverb,'plus ... que',lang__fr,279) },
    { name:(word_class__adverb,'more ... than',lang__en,279) },
    { name:(word_class__adverb,'más ... que',lang__es,279) },
    { name:(word_class__adverb,'moins ... que',lang__fr,280) },
    { name:(word_class__adverb,'less ... than',lang__en,280) },
    { name:(word_class__adverb,'menos ... que',lang__es,280) },
    { name:(word_class__adverb,'autant ... que',lang__fr,281) },
    { name:(word_class__adverb,'as ... as',lang__en,281) },
    { name:(word_class__adverb,'tan ... como',lang__es,281) },
    { name:(word_class__adverb,'la plus',lang__fr,282) },
    { name:(word_class__adverb,'the most',lang__en,282) },
    { name:(word_class__adverb,'la más',lang__es,282) },
    { name:(word_class__adjective,'intéresant',lang__fr,283) },
    { name:(word_class__adjective,'interesting',lang__en,283) },
    { name:(word_class__adjective,'interesante',lang__es,283) },
    { name:(word_class__adjective,'excitant',lang__fr,284) },
    { name:(word_class__adjective,'exciting',lang__en,284) },
    { name:(word_class__adjective,'emocionante',lang__es,284) },
    { name:(word_class__adjective,'drôle',lang__fr,285) },
    { name:(word_class__adjective,'funny',lang__en,285) },
    { name:(word_class__adjective,'graciosa',lang__es,285) },
    { name:(word_class__adjective,'tranquille',lang__fr,286) },
    { name:(word_class__adjective,'quiet',lang__en,286) },
    { name:(word_class__adjective,'tranquilo',lang__es,286) },
    { name:(word_class__adjective,'fort',lang__fr,287) },
    { name:(word_class__adjective,'loud',lang__en,287) },
    { name:(word_class__adjective,'alto',lang__es,287) },
    { name:(word_class__adjective,'confortable',lang__fr,288) },
    { name:(word_class__adjective,'comfortable',lang__en,288) },
    { name:(word_class__adjective,'cómoda',lang__es,288) },
    { name:(word_class__adjective,'étrange',lang__fr,289) },
    { name:(word_class__adjective,'strange',lang__en,289) },
    { name:(word_class__adjective,'peculiar',lang__es,289) },
    { name:(word_class__adjective,'sécuritaire',lang__fr,290) },
    { name:(word_class__adjective,'safe',lang__en,290) },
    { name:(word_class__adjective,'segura',lang__es,290) },
    { name:(word_class__adjective,'dangeureux',lang__fr,291) },
    { name:(word_class__adjective,'dangerous',lang__en,291) },
    { name:(word_class__adjective,'peligroso',lang__es,291) },
    { name:(word_class__adjective,'facile',lang__fr,292) },
    { name:(word_class__adjective,'easy',lang__en,292) },
    { name:(word_class__adjective,'fácil',lang__es,292) },
    { name:(word_class__adjective,'difficile',lang__fr,293) },
    { name:(word_class__adjective,'hard',lang__en,293) },
    { name:(word_class__adjective,'difícil',lang__es,293) },
    { name:(word_class__adjective,'dur',lang__fr,294) },
    { name:(word_class__adjective,'hard',lang__en,294) },
    { name:(word_class__adjective,'dura',lang__es,294) },
    { name:(word_class__adjective,'possible',lang__fr,295) },
    { name:(word_class__adjective,'possible',lang__en,295) },
    { name:(word_class__adjective,'posible',lang__es,295) },
    { name:(word_class__adjective,'fort',lang__fr,296) },
    { name:(word_class__adjective,'strong',lang__en,296) },
    { name:(word_class__adjective,'fuerte',lang__es,296) },
    { name:(word_class__adjective,'amusant',lang__fr,297) },
    { name:(word_class__adjective,'fun',lang__en,297) },
    { name:(word_class__adjective,'divertido',lang__es,297) },
    { name:(word_class__adjective,'cher',lang__fr,298) },
    { name:(word_class__adjective,'expensive',lang__en,298) },
    { name:(word_class__adjective,'caro',lang__es,298) },
    { name:(word_class__adjective,'bon marché',lang__fr,299) },
    { name:(word_class__adjective,'cheap',lang__en,299) },
    { name:(word_class__adjective,'barato',lang__es,299) },
    { name:(word_class__adjective,'pauvre',lang__fr,300) },
    { name:(word_class__adjective,'poor',lang__en,300) },
    { name:(word_class__adjective,'pobre',lang__es,300) },
    { name:(word_class__adjective,'vrai',lang__fr,301) },
    { name:(word_class__adjective,'true',lang__en,301) },
    { name:(word_class__adjective,'verdad',lang__es,301) },
    { name:(word_class__adjective,'correct',lang__fr,302) },
    { name:(word_class__adjective,'correct',lang__en,302) },
    { name:(word_class__adjective,'correcto',lang__es,302) },
    { name:(word_class__adjective,'favori',lang__fr,303) },
    { name:(word_class__adjective,'favorite',lang__en,303) },
    { name:(word_class__adjective,'favorita',lang__es,303) },
    { name:(word_class__adjective,'préféré',lang__fr,304) },
    { name:(word_class__adjective,'preferred',lang__en,304) },
    { name:(word_class__adjective,'preferida',lang__es,304) },
    { name:(word_class__adjective,'cher',lang__fr,305) },
    { name:(word_class__adjective,'dear',lang__en,305) },
    { name:(word_class__adjective,'querido',lang__es,305) },
    { name:(word_class__adjective,'célèbre',lang__fr,306) },
    { name:(word_class__adjective,'famous',lang__en,306) },
    { name:(word_class__adjective,'famoso',lang__es,306) },
    { name:(word_class__adjective,'populaire',lang__fr,307) },
    { name:(word_class__adjective,'popular',lang__en,307) },
    { name:(word_class__adjective,'famoso',lang__es,307) },
    { name:(word_class__adjective,'connu',lang__fr,308) },
    { name:(word_class__adjective,'known',lang__en,308) },
    { name:(word_class__adjective,'conocido',lang__es,308) },
    { name:(word_class__adjective,'seul',lang__fr,309) },
    { name:(word_class__adjective,'alone',lang__en,309) },
    { name:(word_class__adjective,'solo',lang__es,309) },
    { name:(word_class__adjective,'médicinal',lang__fr,310) },
    { name:(word_class__adjective,'medicinal',lang__en,310) },
    { name:(word_class__adjective,'medicina',lang__es,310) },
    { name:(word_class__adjective,'propre',lang__fr,311) },
    { name:(word_class__adjective,'clean',lang__en,311) },
    { name:(word_class__adjective,'limpia',lang__es,311) },
    { name:(word_class__adjective,'sale',lang__fr,312) },
    { name:(word_class__adjective,'dirty',lang__en,312) },
    { name:(word_class__adjective,'sucio',lang__es,312) },
    { name:(word_class__adjective,'crasseux',lang__fr,313) },
    { name:(word_class__adjective,'filthy',lang__en,313) },
    { name:(word_class__adjective,'aqueroso',lang__es,313) },
    { name:(word_class__conjunction,'ou',lang__fr,314) },
    { name:(word_class__conjunction,'or',lang__en,314) },
    { name:(word_class__conjunction,'o',lang__es,314) },
    { name:(word_class__conjunction,'et',lang__fr,315) },
    { name:(word_class__conjunction,'and',lang__en,315) },
    { name:(word_class__conjunction,'y',lang__es,315) },
    { name:(word_class__conjunction,'mais',lang__fr,316) },
    { name:(word_class__conjunction,'but',lang__en,316) },
    { name:(word_class__conjunction,'pero',lang__es,316) },
    { name:(word_class__conjunction,'parce que',lang__fr,317) },
    { name:(word_class__conjunction,'because',lang__en,317) },
    { name:(word_class__conjunction,'porque',lang__es,317) },
    { name:(word_class__conjunction,'où ',lang__fr,318) },
    { name:(word_class__conjunction,'where',lang__en,318) },
    { name:(word_class__conjunction,'donde',lang__es,318) },
    { name:(word_class__conjunction,'sau',lang__fr,319) },
    { name:(word_class__conjunction,'except',lang__en,319) },
    { name:(word_class__conjunction,'excepto',lang__es,319) },
    { name:(word_class__adjective,'foncé',lang__fr,320) },
    { name:(word_class__adjective,'dark',lang__en,320) },
    { name:(word_class__adjective,'moreno',lang__es,320) },
    { name:(word_class__adjective,'blond',lang__fr,321) },
    { name:(word_class__adjective,'blonde',lang__en,321) },
    { name:(word_class__adjective,'rubio',lang__es,321) },
    { name:(word_class__adjective,'plein',lang__fr,322) },
    { name:(word_class__adjective,'full',lang__en,322) },
    { name:(word_class__adjective,'lleno',lang__es,322) },
    { name:(word_class__adjective,'obscur',lang__fr,323) },
    { name:(word_class__adjective,'dark',lang__en,323) },
    { name:(word_class__adjective,'obscuro',lang__es,323) },
    { name:(word_class__adjective,'nuageux',lang__fr,324) },
    { name:(word_class__adjective,'cloudy',lang__en,324) },
    { name:(word_class__adjective,'nublado',lang__es,324) },
    { name:(word_class__adjective,'ensoleillé',lang__fr,325) },
    { name:(word_class__adjective,'sunny',lang__en,325) },
    { name:(word_class__adjective,'soleado',lang__es,325) },
    { name:(word_class__adjective,'sec',lang__fr,326) },
    { name:(word_class__adjective,'dry',lang__en,326) },
    { name:(word_class__adjective,'seco',lang__es,326) },
    { name:(word_class__adjective,'végétalien',lang__fr,327) },
    { name:(word_class__adjective,'vegan',lang__en,327) },
    { name:(word_class__adjective,'vegano',lang__es,327) },
    { name:(word_class__adjective,'léger',lang__fr,328) },
    { name:(word_class__adjective,'light',lang__en,328) },
    { name:(word_class__adjective,'ligera',lang__es,328) },
    { name:(word_class__adjective,'lourd',lang__fr,329) },
    { name:(word_class__adjective,'heavy',lang__en,329) },
    { name:(word_class__adjective,'pesado',lang__es,329) },
    { name:(word_class__adjective,'rapide',lang__fr,330) },
    { name:(word_class__adjective,'fast',lang__en,330) },
    { name:(word_class__adjective,'rapido',lang__es,330) },
    { name:(4,'lentement',lang__fr,331) },
    { name:(4,'slowly',lang__en,331) },
    { name:(4,'despacio',lang__es,331) },
    { name:(word_class__adjective,'lent',lang__fr,332) },
    { name:(word_class__adjective,'slow',lang__en,332) },
    { name:(word_class__adjective,'lento',lang__es,332) },
    { name:(word_class__adjective,'sauvage',lang__fr,333) },
    { name:(word_class__adjective,'wild',lang__en,333) },
    { name:(word_class__adjective,'sylvestre',lang__es,333) },
    { name:(word_class__adjective,'sauvage',lang__fr,334) },
    { name:(word_class__adjective,'wild',lang__en,334) },
    { name:(word_class__adjective,'salvaje',lang__es,334) },
    { name:(word_class__adjective,'libre',lang__fr,335) },
    { name:(word_class__adjective,'free',lang__en,335) },
    { name:(word_class__adjective,'libro',lang__es,335) },
    { name:(word_class__adjective,'simple',lang__fr,336) },
    { name:(word_class__adjective,'simple',lang__en,336) },
    { name:(word_class__adjective,'sencilla',lang__es,336) },
    { name:(word_class__adjective,'malade',lang__fr,337) },
    { name:(word_class__adjective,'sick',lang__en,337) },
    { name:(word_class__adjective,'enfermo',lang__es,337) },
    { name:(word_class__adjective,'en santé',lang__fr,338) },
    { name:(word_class__adjective,'healthy',lang__en,338) },
    { name:(word_class__adjective,'saludable',lang__es,338) },
    { name:(word_class__adjective,'fatigué',lang__fr,339) },
    { name:(word_class__adjective,'tired',lang__en,339) },
    { name:(word_class__adjective,'cansado',lang__es,339) },
    { name:(word_class__adjective,'somnolant',lang__fr,340) },
    { name:(word_class__adjective,'sleepy',lang__en,340) },
    { name:(word_class__adjective,'sueño',lang__es,340) },
    { name:(word_class__adjective,'endormi',lang__fr,341) },
    { name:(word_class__adjective,'asleep',lang__en,341) },
    { name:(word_class__adjective,'dormida',lang__es,341) },
    { name:(word_class__adjective,'apeuré',lang__fr,342) },
    { name:(word_class__adjective,'afraid',lang__en,342) },
    { name:(word_class__adjective,'miedo',lang__es,342) },
    { name:(word_class__adjective,'aveugle',lang__fr,343) },
    { name:(word_class__adjective,'blind',lang__en,343) },
    { name:(word_class__adjective,'ciego',lang__es,343) },
    { name:(word_class__adjective,'intelligent',lang__fr,344) },
    { name:(word_class__adjective,'intelligent',lang__en,344) },
    { name:(word_class__adjective,'inteligente',lang__es,344) },
    { name:(word_class__adjective,'sympathique',lang__fr,345) },
    { name:(word_class__adjective,'nice',lang__en,345) },
    { name:(word_class__adjective,'simpático',lang__es,345) },
    { name:(word_class__adjective,'studieux',lang__fr,346) },
    { name:(word_class__adjective,'studious',lang__en,346) },
    { name:(word_class__adjective,'estudioso',lang__es,346) },
    { name:(word_class__adjective,'responsable',lang__fr,347) },
    { name:(word_class__adjective,'responsible',lang__en,347) },
    { name:(word_class__adjective,'responsable',lang__es,347) },
    { name:(word_class__adjective,'aimable',lang__fr,348) },
    { name:(word_class__adjective,'nice',lang__en,348) },
    { name:(word_class__adjective,'amable',lang__es,348) },
    { name:(word_class__adjective,'tranquille',lang__fr,349) },
    { name:(word_class__adjective,'calm',lang__en,349) },
    { name:(word_class__adjective,'tranquilo',lang__es,349) },
    { name:(word_class__adjective,'paresseux',lang__fr,350) },
    { name:(word_class__adjective,'lazy',lang__en,350) },
    { name:(word_class__adjective,'perezosos',lang__es,350) },
    { name:(word_class__adjective,'fou',lang__fr,351) },
    { name:(word_class__adjective,'crazy',lang__en,351) },
    { name:(word_class__adjective,'loco',lang__es,351) },
    { name:(word_class__adjective,'même',lang__fr,352) },
    { name:(word_class__adjective,'same',lang__en,352) },
    { name:(word_class__adjective,'mismo',lang__es,352) },
    { name:(word_class__adjective,'prochain',lang__fr,353) },
    { name:(word_class__adjective,'next',lang__en,353) },
    { name:(word_class__adjective,'siguiente',lang__es,353) },
    { name:(word_class__adjective,'prochain',lang__fr,354) },
    { name:(word_class__adjective,'next',lang__en,354) },
    { name:(word_class__adjective,'próxima',lang__es,354) },
    { name:(word_class__adjective,'différent',lang__fr,355) },
    { name:(word_class__adjective,'different',lang__en,355) },
    { name:(word_class__adjective,'diferente',lang__es,355) },
    { name:(word_class__adjective,'chaque',lang__fr,356) },
    { name:(word_class__adjective,'every',lang__en,356) },
    { name:(word_class__adjective,'todo',lang__es,356) },
    { name:(word_class__adjective,'autre',lang__fr,357) },
    { name:(word_class__adjective,'other',lang__en,357) },
    { name:(word_class__adjective,'otro',lang__es,357) },
    { name:(word_class__adjective,'tous deux',lang__fr,358) },
    { name:(word_class__adjective,'both',lang__en,358) },
    { name:(word_class__adjective,'ambas',lang__es,358) },
    { name:(word_class__adjective,'aussi',lang__fr,359) },
    { name:(word_class__adjective,'either',lang__en,359) },
    { name:(word_class__adjective,'tampoco',lang__es,359) },
    { name:(word_class__adjective,'dernier',lang__fr,360) },
    { name:(word_class__adjective,'last',lang__en,360) },
    { name:(word_class__adjective,'último',lang__es,360) },
    { name:(word_class__adjective,'premier',lang__fr,361) },
    { name:(word_class__adjective,'first',lang__en,361) },
    { name:(word_class__adjective,'primer',lang__es,361) },
    { name:(word_class__adjective,'deuxième',lang__fr,362) },
    { name:(word_class__adjective,'second',lang__en,362) },
    { name:(word_class__adjective,'segundo',lang__es,362) },
    { name:(word_class__adjective,'troisième',lang__fr,363) },
    { name:(word_class__adjective,'third',lang__en,363) },
    { name:(word_class__adjective,'tercera',lang__es,363) },
    { name:(word_class__adjective,'bien',lang__fr,364) },
    { name:(word_class__adjective,'okay',lang__en,364) },
    { name:(word_class__adjective,'bien',lang__es,364) },
    { name:(word_class__adjective,'heureux',lang__fr,365) },
    { name:(word_class__adjective,'happy',lang__en,365) },
    { name:(word_class__adjective,'feliz',lang__es,365) },
    { name:(word_class__adjective,'content',lang__fr,366) },
    { name:(word_class__adjective,'content',lang__en,366) },
    { name:(word_class__adjective,'contento',lang__es,366) },
    { name:(word_class__adjective,'excité',lang__fr,367) },
    { name:(word_class__adjective,'excited',lang__en,367) },
    { name:(word_class__adjective,'emocionada',lang__es,367) },
    { name:(word_class__adjective,'confortable',lang__fr,368) },
    { name:(word_class__adjective,'comfortable',lang__en,368) },
    { name:(word_class__adjective,'confortable',lang__es,368) },
    { name:(word_class__adjective,'satisfait',lang__fr,369) },
    { name:(word_class__adjective,'satisfied',lang__en,369) },
    { name:(word_class__adjective,'satisfecha',lang__es,369) },
    { name:(word_class__adjective,'mal',lang__fr,370) },
    { name:(word_class__adjective,'unwell',lang__en,370) },
    { name:(word_class__adjective,'mal',lang__es,370) },
    { name:(word_class__adjective,'triste',lang__fr,371) },
    { name:(word_class__adjective,'sad',lang__en,371) },
    { name:(word_class__adjective,'triste',lang__es,371) },
    { name:(word_class__adjective,'fâché',lang__fr,372) },
    { name:(word_class__adjective,'angry',lang__en,372) },
    { name:(word_class__adjective,'enojado',lang__es,372) },
    { name:(word_class__adjective,'fâché',lang__fr,373) },
    { name:(word_class__adjective,'angry',lang__en,373) },
    { name:(word_class__adjective,'enfadado',lang__es,373) },
    { name:(word_class__adjective,'préoccupé',lang__fr,374) },
    { name:(word_class__adjective,'preoccupied',lang__en,374) },
    { name:(word_class__adjective,'preocupada',lang__es,374) },
    { name:(word_class__adjective,'abattu',lang__fr,375) },
    { name:(word_class__adjective,'dejected',lang__en,375) },
    { name:(word_class__adjective,'abatido',lang__es,375) },
    { name:(word_class__adjective,'ennuyé',lang__fr,376) },
    { name:(word_class__adjective,'bored',lang__en,376) },
    { name:(word_class__adjective,'aburrido',lang__es,376) },
    { name:(word_class__adjective,'surpris',lang__fr,377) },
    { name:(word_class__adjective,'surprised',lang__en,377) },
    { name:(word_class__adjective,'sorprendido',lang__es,377);] })