

LOCK TABLES `word_definition` WRITE;
/*!40000 ALTER TABLE `word_definition` DISABLE KEYS */;
INSERT INTO `word_definition` VALUES (1,'article défini féminin singulier')
WordDefinition.create(definition: "article défini masculin singulier")
WordDefinition.create(definition: "article défini féminin pluriel")
WordDefinition.create(definition: "Article défini masculin pluriel")
WordDefinition.create(definition: "Article indéfini féminin singulier")
WordDefinition.create(definition: "Article indéfini masculin singulier")
WordDefinition.create(definition: "être quelque chose, intrinsèquement")
WordDefinition.create(definition: "être dans un état quelconque, temporairement")
WordDefinition.create(definition: "avoir l\'air de, ressembler")
WordDefinition.create(definition: "qui est probable, attendu, souhaité")
WordDefinition.create(definition: "vouloir, désirer quelque chose")
WordDefinition.create(definition: "savoir quelque chose")
WordDefinition.create(definition: "avoir la capacité de faire quelque chose")
WordDefinition.create(definition: "se placer en position assise")
WordDefinition.create(definition: "se lever")
WordDefinition.create(definition: "se déplacer à pied")
WordDefinition.create(definition: "se déplacer à pied, plus rapidement qu\'à la marche")
WordDefinition.create(definition: "se déplacer à la nage")
WordDefinition.create(definition: "se déplacer en volant")
WordDefinition.create(definition: "se mouvoir en dansant")
WordDefinition.create(definition: "changer de direction")
WordDefinition.create(definition: "se déplacer à pied")
WordDefinition.create(definition: "pleuvoir")
WordDefinition.create(definition: "neiger")
WordDefinition.create(definition: "vivre")
WordDefinition.create(definition: "aller")
WordDefinition.create(definition: "partir, sortir")
WordDefinition.create(definition: "arriver")
WordDefinition.create(definition: "entrer")
WordDefinition.create(definition: "venir")
WordDefinition.create(definition: "voyager")
WordDefinition.create(definition: "visiter")
WordDefinition.create(definition: "passer")
WordDefinition.create(definition: "rester")
WordDefinition.create(definition: "retourner")
WordDefinition.create(definition: "reculer")
WordDefinition.create(definition: "disparaître")
WordDefinition.create(definition: "habiter")
WordDefinition.create(definition: "avoir")
WordDefinition.create(definition: "devoir")
WordDefinition.create(definition: "trouver, rencontrer")
WordDefinition.create(definition: "bouger")
WordDefinition.create(definition: "prendre")
WordDefinition.create(definition: "prendre, baiser")
WordDefinition.create(definition: "transporter")
WordDefinition.create(definition: "apporter")
WordDefinition.create(definition: "envoyer quelque chose quelque part")
WordDefinition.create(definition: "envoyer par autorité, ordonner")
WordDefinition.create(definition: "changer quelque chose")
WordDefinition.create(definition: "ouvrir quelque chose")
WordDefinition.create(definition: "fermer quelque chose")
WordDefinition.create(definition: "allumer un appareil, un moteur")
WordDefinition.create(definition: "fermer un appareil, un moteur")
WordDefinition.create(definition: "briser, rompre quelque chose")
WordDefinition.create(definition: "terminer quelque chose")
WordDefinition.create(definition: "préparer quelque chose")
WordDefinition.create(definition: "mettre en équilibre")
WordDefinition.create(definition: "abandonner")
WordDefinition.create(definition: "rendre moins cher")
WordDefinition.create(definition: "accepter, inclure")
WordDefinition.create(definition: "élire quelque chose, prendre une décision")
WordDefinition.create(definition: "planifier quelque chose")
WordDefinition.create(definition: "faire une activité")
WordDefinition.create(definition: "essayer quelque chose")
WordDefinition.create(definition: "essayer de faire quelque chose")
WordDefinition.create(definition: "pratiquer une activité")
WordDefinition.create(definition: "débuter, commencer quelque chose")
WordDefinition.create(definition: "débuter, commencer quelque chose")
WordDefinition.create(definition: "continuer quelque chose")
WordDefinition.create(definition: "arrêter de faire quelque chose")
WordDefinition.create(definition: "attendre quelque chose")
WordDefinition.create(definition: "finir quelque chose")
WordDefinition.create(definition: "répéter quelque chose")
WordDefinition.create(definition: "lorsque quelque chose se produit")
WordDefinition.create(definition: "cesser de vivre")
WordDefinition.create(definition: "se reposer")
WordDefinition.create(definition: "dormir")
WordDefinition.create(definition: "aller au lit, se coucher")
WordDefinition.create(definition: "rêver")
WordDefinition.create(definition: "ronfler")
WordDefinition.create(definition: "se réveiller")
WordDefinition.create(definition: "avoir mal, souffrir")
WordDefinition.create(definition: "regarder")
WordDefinition.create(definition: "voir")
WordDefinition.create(definition: "entendre")
WordDefinition.create(definition: "écouter")
WordDefinition.create(definition: "boire")
WordDefinition.create(definition: "manger")
WordDefinition.create(definition: "se vêtir, porter un vêtement")
WordDefinition.create(definition: "sentir (sentiment)")
WordDefinition.create(definition: "qui plait à quelqu\'un")
WordDefinition.create(definition: "pleurer")
WordDefinition.create(definition: "mourir")
WordDefinition.create(definition: "se reposer")
WordDefinition.create(definition: "dormir")
WordDefinition.create(definition: "aller se coucher")
WordDefinition.create(definition: "rêver")
WordDefinition.create(definition: "ronfler")
WordDefinition.create(definition: "se réveiller")
WordDefinition.create(definition: "avoir mal")
WordDefinition.create(definition: "regarder")
WordDefinition.create(definition: "regarder")
WordDefinition.create(definition: "entendre")
WordDefinition.create(definition: "écouter")
WordDefinition.create(definition: "boire")
WordDefinition.create(definition: "manger")
WordDefinition.create(definition: "aller dîner")
WordDefinition.create(definition: "souper")
WordDefinition.create(definition: "déjeûner")
WordDefinition.create(definition: "se vêtir")
WordDefinition.create(definition: "aimer")
WordDefinition.create(definition: "apprécier")
WordDefinition.create(definition: "préférer")
WordDefinition.create(definition: "se préoccuper")
WordDefinition.create(definition: "haïr")
WordDefinition.create(definition: "s\'ennuyer de quelqu\'un, quelque chose")
WordDefinition.create(definition: "penser")
WordDefinition.create(definition: "croire")
WordDefinition.create(definition: "décider")
WordDefinition.create(definition: "s\'intéresser")
WordDefinition.create(definition: "apprendre")
WordDefinition.create(definition: "étudier")
WordDefinition.create(definition: "enseigner")
WordDefinition.create(definition: "se rappeller")
WordDefinition.create(definition: "comprendre")
WordDefinition.create(definition: "comprendre")
WordDefinition.create(definition: "oublier")
WordDefinition.create(definition: "avoir besoin de")
WordDefinition.create(definition: "chercher")
WordDefinition.create(definition: "demander, passer une commande")
WordDefinition.create(definition: "servir (un repas, une boisson)")
WordDefinition.create(definition: "fournir")
WordDefinition.create(definition: "prendre une douche")
WordDefinition.create(definition: "laver (quelqu\'un)")
WordDefinition.create(definition: "laver (quelque chose)")
WordDefinition.create(definition: "s\'occuper de")
WordDefinition.create(definition: "brosser")
WordDefinition.create(definition: "réprarer")
WordDefinition.create(definition: "porter (vêtement)")
WordDefinition.create(definition: "utiliser")
WordDefinition.create(definition: "mettre (vêtement)")
WordDefinition.create(definition: "parler")
WordDefinition.create(definition: "lire")
WordDefinition.create(definition: "jouer (d\'un instrument)")
WordDefinition.create(definition: "fumer")
WordDefinition.create(definition: "conduire (un véhicule)")
WordDefinition.create(definition: "monter (un véhicule, objet)")
WordDefinition.create(definition: "ventiler")
WordDefinition.create(definition: "donner")
WordDefinition.create(definition: "recevoir")
WordDefinition.create(definition: "payer")
WordDefinition.create(definition: "acheter")
WordDefinition.create(definition: "réserver")
WordDefinition.create(definition: "pêcher")
WordDefinition.create(definition: "inviter")
WordDefinition.create(definition: "connaître (quelqu\'un)")
WordDefinition.create(definition: "rencontrer (quelqu\'un)")
WordDefinition.create(definition: "rejoindre")
WordDefinition.create(definition: "accompagner")
WordDefinition.create(definition: "demander")
WordDefinition.create(definition: "répondre")
WordDefinition.create(definition: "dire")
WordDefinition.create(definition: "appeller")
WordDefinition.create(definition: "avoir une conversation")
WordDefinition.create(definition: "arrimer")
WordDefinition.create(definition: "écrire")
WordDefinition.create(definition: "cuisiner")
WordDefinition.create(definition: "dessiner")
WordDefinition.create(definition: "peinturer")
WordDefinition.create(definition: "chanter")
WordDefinition.create(definition: "travailler")
WordDefinition.create(definition: "jouer (à un jeu)")
WordDefinition.create(definition: "passer (un examen)")
WordDefinition.create(definition: "gagner")
WordDefinition.create(definition: "perdre")
WordDefinition.create(definition: "prier")
WordDefinition.create(definition: "empoisonner")
WordDefinition.create(definition: "une définition")
WordDefinition.create(definition: "où")
WordDefinition.create(definition: "quand")
WordDefinition.create(definition: "what, quel/qu\'est-ce")
WordDefinition.create(definition: "qui")
WordDefinition.create(definition: "pourquoi")
WordDefinition.create(definition: "lequel")
WordDefinition.create(definition: "combien (inquantifiable)")
WordDefinition.create(definition: "combien (quantifiable)")
WordDefinition.create(definition: "comment")
WordDefinition.create(definition: "ici")
WordDefinition.create(definition: "proche, pas loin")
WordDefinition.create(definition: "par là")
WordDefinition.create(definition: "là, là-bas")
WordDefinition.create(definition: "là, là-bas")
WordDefinition.create(definition: "partout")
WordDefinition.create(definition: "près de, proche de")
WordDefinition.create(definition: "à côté de")
WordDefinition.create(definition: "lointain, loin")
WordDefinition.create(definition: "à l\'intérieur, en dedans")
WordDefinition.create(definition: "par dessus")
WordDefinition.create(definition: "par dessus, en haut de")
WordDefinition.create(definition: "sous, en dessous")
WordDefinition.create(definition: "derrière")
WordDefinition.create(definition: "en avant de, devant")
WordDefinition.create(definition: "entre")
WordDefinition.create(definition: "dans, à l\'intérieur")
WordDefinition.create(definition: "en bas")
WordDefinition.create(definition: "en haut")
WordDefinition.create(definition: "en arrière")
WordDefinition.create(definition: "dehors, à l\'extérieur")
WordDefinition.create(definition: "à travers")
WordDefinition.create(definition: "le long de")
WordDefinition.create(definition: "vers")
WordDefinition.create(definition: "par ici")
WordDefinition.create(definition: "très")
WordDefinition.create(definition: "plus, une plus grande quantité")
WordDefinition.create(definition: "extra")
WordDefinition.create(definition: "trop")
WordDefinition.create(definition: "beaucoup")
WordDefinition.create(definition: "peu")
WordDefinition.create(definition: "plusieurs")
WordDefinition.create(definition: "quelques")
WordDefinition.create(definition: "les deux")
WordDefinition.create(definition: "complètement")
WordDefinition.create(definition: "aucun")
WordDefinition.create(definition: "quelque")
WordDefinition.create(definition: "quelques")
WordDefinition.create(definition: "presque")
WordDefinition.create(definition: "maintenant")
WordDefinition.create(definition: "une autre fois")
WordDefinition.create(definition: "cette fois-ci")
WordDefinition.create(definition: "en ce moment même")
WordDefinition.create(definition: "un jour")
WordDefinition.create(definition: "tout le temps")
WordDefinition.create(definition: "il y a longtemps")
WordDefinition.create(definition: "et puis, après")
WordDefinition.create(definition: "avant, précédemment")
WordDefinition.create(definition: "après, ensuite")
WordDefinition.create(definition: "autour de (temps)")
WordDefinition.create(definition: "pour (échéance)")
WordDefinition.create(definition: "plus (elle ne fait plus quelque chose)")
WordDefinition.create(definition: "qui vient")
WordDefinition.create(definition: "prochain")
WordDefinition.create(definition: "plus tard")
WordDefinition.create(definition: "dernier, passé")
WordDefinition.create(definition: "premier")
WordDefinition.create(definition: "tôt")
WordDefinition.create(definition: "tard")
WordDefinition.create(definition: "bientôt")
WordDefinition.create(definition: "il y a (temps dans le passé)")
WordDefinition.create(definition: "finalement, pour finir")
WordDefinition.create(definition: "jamais")
WordDefinition.create(definition: "jamais")
WordDefinition.create(definition: "desfois")
WordDefinition.create(definition: "de temps en temps")
WordDefinition.create(definition: "normalement")
WordDefinition.create(definition: "d\'habitude, habituellement")
WordDefinition.create(definition: "généralement")
WordDefinition.create(definition: "fréquemment")
WordDefinition.create(definition: "souvent")
WordDefinition.create(definition: "toujours, tout le temps, en tout temps")
WordDefinition.create(definition: "à")
WordDefinition.create(definition: "à, en (là où quelque chose est)")
WordDefinition.create(definition: "pour")
WordDefinition.create(definition: "avec")
WordDefinition.create(definition: "sans")
WordDefinition.create(definition: "avec toi")
WordDefinition.create(definition: "avec moi")
WordDefinition.create(definition: "de")
WordDefinition.create(definition: "désigner une journée")
WordDefinition.create(definition: "à (heure)")
WordDefinition.create(definition: "par")
WordDefinition.create(definition: "pendant")
WordDefinition.create(definition: "jusqu\'à")
WordDefinition.create(definition: "après")
WordDefinition.create(definition: "excepté")
WordDefinition.create(definition: "être plus <...> que")
WordDefinition.create(definition: "moins <...> que")
WordDefinition.create(definition: "autant <...> que")
WordDefinition.create(definition: "le/la plus")
WordDefinition.create(definition: "intéresant")
WordDefinition.create(definition: "excitant")
WordDefinition.create(definition: "drôle")
WordDefinition.create(definition: "tranquille")
WordDefinition.create(definition: "fort (son)")
WordDefinition.create(definition: "confortable")
WordDefinition.create(definition: "étrange, bizarre")
WordDefinition.create(definition: "sécuritaire")
WordDefinition.create(definition: "dangeureux")
WordDefinition.create(definition: "facile")
WordDefinition.create(definition: "difficile")
WordDefinition.create(definition: "dur (difficulté)")
WordDefinition.create(definition: "possible")
WordDefinition.create(definition: "fort (force)")
WordDefinition.create(definition: "amusant")
WordDefinition.create(definition: "cher (coût)")
WordDefinition.create(definition: "pas cher")
WordDefinition.create(definition: "pauvre")
WordDefinition.create(definition: "vrai")
WordDefinition.create(definition: "correct (validité)")
WordDefinition.create(definition: "favori, préféré")
WordDefinition.create(definition: "préféré")
WordDefinition.create(definition: "cher (affection)")
WordDefinition.create(definition: "célèbre")
WordDefinition.create(definition: "populaire")
WordDefinition.create(definition: "connu")
WordDefinition.create(definition: "seul")
WordDefinition.create(definition: "médicinal")
WordDefinition.create(definition: "propre")
WordDefinition.create(definition: "sale")
WordDefinition.create(definition: "crasseux")
WordDefinition.create(definition: "ou")
WordDefinition.create(definition: "et")
WordDefinition.create(definition: "mais")
WordDefinition.create(definition: "parce que")
WordDefinition.create(definition: "où")
WordDefinition.create(definition: "sauf")
WordDefinition.create(definition: "(brun) foncé (cheveux, teint)")
WordDefinition.create(definition: "blond")
WordDefinition.create(definition: "plein")
WordDefinition.create(definition: "obscur, foncé")
WordDefinition.create(definition: "nuageux")
WordDefinition.create(definition: "ensoleillé")
WordDefinition.create(definition: "sec")
WordDefinition.create(definition: "végétalien")
WordDefinition.create(definition: "léger")
WordDefinition.create(definition: "lourd, pesant")
WordDefinition.create(definition: "rapide, vite")
WordDefinition.create(definition: "lentement")
WordDefinition.create(definition: "lent")
WordDefinition.create(definition: "sauvage")
WordDefinition.create(definition: "sauvage")
WordDefinition.create(definition: "libre")
WordDefinition.create(definition: "simple")
WordDefinition.create(definition: "malade")
WordDefinition.create(definition: "en santé")
WordDefinition.create(definition: "fatigué")
WordDefinition.create(definition: "somnolant")
WordDefinition.create(definition: "endormi")
WordDefinition.create(definition: "apeuré")
WordDefinition.create(definition: "aveugle")
WordDefinition.create(definition: "intelligent")
WordDefinition.create(definition: "sympathique")
WordDefinition.create(definition: "studieux")
WordDefinition.create(definition: "responsable")
WordDefinition.create(definition: "aimable")
WordDefinition.create(definition: "tranquille")
WordDefinition.create(definition: "paresseux")
WordDefinition.create(definition: "fou")
WordDefinition.create(definition: "même (pareil)")
WordDefinition.create(definition: "prochain")
WordDefinition.create(definition: "prochain")
WordDefinition.create(definition: "différent")
WordDefinition.create(definition: "chaque, à tout les")
WordDefinition.create(definition: "autre")
WordDefinition.create(definition: "tous deux")
WordDefinition.create(definition: "aussi, non plus")
WordDefinition.create(definition: "dernier")
WordDefinition.create(definition: "premier")
WordDefinition.create(definition: "deuxième")
WordDefinition.create(definition: "troisième")
WordDefinition.create(definition: "bien (émotion, bien aller)")
WordDefinition.create(definition: "heureux")
WordDefinition.create(definition: "content")
WordDefinition.create(definition: "excité")
WordDefinition.create(definition: "confortable")
WordDefinition.create(definition: "satisfait")
WordDefinition.create(definition: "pas bien, mal")
WordDefinition.create(definition: "triste")
WordDefinition.create(definition: "fâché")
WordDefinition.create(definition: "fâché (esp)")
WordDefinition.create(definition: "préoccupé, inquiet")
WordDefinition.create(definition: "abattu (moral)")
WordDefinition.create(definition: "ennuyé")
WordDefinition.create(definition: "surpris'";