lang__en = Language.find_by({name: 'English', shorthand: 'en', active: true})
lang__fr = Language.find_by({name: 'Français', shorthand: 'fr', active: true})
lang__es = Language.find_by({name: 'Español', shorthand: 'es', active: true})
lang__ca = Language.find_by({name: 'Catalan', shorthand: 'ca', active: true})
lang__no = Language.find_by({name: 'Norsk', shorthand: 'no', active: true})

Word.create(loc: "ser", word_definition: WordDefinition.create_or_find_by(definition: "être quelque chose, intrinsèquement"), language: lang__es, wordable: Verb.create)
Word.create(loc: "être", word_definition: WordDefinition.create_or_find_by(definition: "être quelque chose, intrinsèquement"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to be", word_definition: WordDefinition.create_or_find_by(definition: "être quelque chose, intrinsèquement"), language: lang__en, wordable: Verb.create)
Word.create(loc: "estar", word_definition: WordDefinition.create_or_find_by(definition: "être dans un état quelconque, temporairement"), language: lang__es, wordable: Verb.create)
Word.create(loc: "être", word_definition: WordDefinition.create_or_find_by(definition: "être dans un état quelconque, temporairement"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to be", word_definition: WordDefinition.create_or_find_by(definition: "être dans un état quelconque, temporairement"), language: lang__en, wordable: Verb.create)
Word.create(loc: "parecer", word_definition: WordDefinition.create_or_find_by(definition: "avoir l\'air de, ressembler"), language: lang__es, wordable: Verb.create)
Word.create(loc: "paraître", word_definition: WordDefinition.create_or_find_by(definition: "avoir l\'air de, ressembler"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to seem", word_definition: WordDefinition.create_or_find_by(definition: "avoir l\'air de, ressembler"), language: lang__en, wordable: Verb.create)
Word.create(loc: "deber", word_definition: WordDefinition.create_or_find_by(definition: "qui est probable, attendu, souhaité"), language: lang__es, wordable: Verb.create)
Word.create(loc: "devoir", word_definition: WordDefinition.create_or_find_by(definition: "qui est probable, attendu, souhaité"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "querer", word_definition: WordDefinition.create_or_find_by(definition: "vouloir, désirer quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "vouloir", word_definition: WordDefinition.create_or_find_by(definition: "vouloir, désirer quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to want", word_definition: WordDefinition.create_or_find_by(definition: "vouloir, désirer quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "saber", word_definition: WordDefinition.create_or_find_by(definition: "savoir quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "savoir", word_definition: WordDefinition.create_or_find_by(definition: "savoir quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to know", word_definition: WordDefinition.create_or_find_by(definition: "savoir quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "poder", word_definition: WordDefinition.create_or_find_by(definition: "avoir la capacité de faire quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "pouvoir", word_definition: WordDefinition.create_or_find_by(definition: "avoir la capacité de faire quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to be able to", word_definition: WordDefinition.create_or_find_by(definition: "avoir la capacité de faire quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "sentar", word_definition: WordDefinition.create_or_find_by(definition: "se placer en position assise"), language: lang__es, wordable: Verb.create)
Word.create(loc: "asseoir", word_definition: WordDefinition.create_or_find_by(definition: "se placer en position assise"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to sit", word_definition: WordDefinition.create_or_find_by(definition: "se placer en position assise"), language: lang__en, wordable: Verb.create)
Word.create(loc: "levantar", word_definition: WordDefinition.create_or_find_by(definition: "se lever"), language: lang__es, wordable: Verb.create)
Word.create(loc: "lever", word_definition: WordDefinition.create_or_find_by(definition: "se lever"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to get up", word_definition: WordDefinition.create_or_find_by(definition: "se lever"), language: lang__en, wordable: Verb.create)
Word.create(loc: "caminar", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer à pied"), language: lang__es, wordable: Verb.create)
Word.create(loc: "marcher", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer à pied"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to walk", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer à pied"), language: lang__en, wordable: Verb.create)
Word.create(loc: "correr", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer à pied, plus rapidement qu\'à la marche"), language: lang__es, wordable: Verb.create)
Word.create(loc: "courir", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer à pied, plus rapidement qu\'à la marche"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to run", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer à pied, plus rapidement qu\'à la marche"), language: lang__en, wordable: Verb.create)
Word.create(loc: "nadar", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer à la nage"), language: lang__es, wordable: Verb.create)
Word.create(loc: "nager", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer à la nage"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to swim", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer à la nage"), language: lang__en, wordable: Verb.create)
Word.create(loc: "volar", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer en volant"), language: lang__es, wordable: Verb.create)
Word.create(loc: "voler", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer en volant"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to fly", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer en volant"), language: lang__en, wordable: Verb.create)
Word.create(loc: "bailar", word_definition: WordDefinition.create_or_find_by(definition: "se mouvoir en dansant"), language: lang__es, wordable: Verb.create)
Word.create(loc: "danser", word_definition: WordDefinition.create_or_find_by(definition: "se mouvoir en dansant"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to dance", word_definition: WordDefinition.create_or_find_by(definition: "se mouvoir en dansant"), language: lang__en, wordable: Verb.create)
Word.create(loc: "girar", word_definition: WordDefinition.create_or_find_by(definition: "changer de direction"), language: lang__es, wordable: Verb.create)
Word.create(loc: "tourner", word_definition: WordDefinition.create_or_find_by(definition: "changer de direction"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to turn", word_definition: WordDefinition.create_or_find_by(definition: "changer de direction"), language: lang__en, wordable: Verb.create)
Word.create(loc: "andar", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer à pied"), language: lang__es, wordable: Verb.create)
Word.create(loc: "promener", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer à pied"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to walk", word_definition: WordDefinition.create_or_find_by(definition: "se déplacer à pied"), language: lang__en, wordable: Verb.create)
Word.create(loc: "llover", word_definition: WordDefinition.create_or_find_by(definition: "pleuvoir"), language: lang__es, wordable: Verb.create)
Word.create(loc: "pleuvoir", word_definition: WordDefinition.create_or_find_by(definition: "pleuvoir"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to rain", word_definition: WordDefinition.create_or_find_by(definition: "pleuvoir"), language: lang__en, wordable: Verb.create)
Word.create(loc: "nevar", word_definition: WordDefinition.create_or_find_by(definition: "neiger"), language: lang__es, wordable: Verb.create)
Word.create(loc: "neiger", word_definition: WordDefinition.create_or_find_by(definition: "neiger"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to snow", word_definition: WordDefinition.create_or_find_by(definition: "neiger"), language: lang__en, wordable: Verb.create)
Word.create(loc: "vivir", word_definition: WordDefinition.create_or_find_by(definition: "vivre"), language: lang__es, wordable: Verb.create)
Word.create(loc: "vivre", word_definition: WordDefinition.create_or_find_by(definition: "vivre"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to live", word_definition: WordDefinition.create_or_find_by(definition: "vivre"), language: lang__en, wordable: Verb.create)
Word.create(loc: "ir", word_definition: WordDefinition.create_or_find_by(definition: "aller"), language: lang__es, wordable: Verb.create)
Word.create(loc: "aller", word_definition: WordDefinition.create_or_find_by(definition: "aller"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to go", word_definition: WordDefinition.create_or_find_by(definition: "aller"), language: lang__en, wordable: Verb.create)
Word.create(loc: "salir", word_definition: WordDefinition.create_or_find_by(definition: "partir, sortir"), language: lang__es, wordable: Verb.create)
Word.create(loc: "partir", word_definition: WordDefinition.create_or_find_by(definition: "partir, sortir"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to leave", word_definition: WordDefinition.create_or_find_by(definition: "partir, sortir"), language: lang__en, wordable: Verb.create)
Word.create(loc: "llegar", word_definition: WordDefinition.create_or_find_by(definition: "arriver"), language: lang__es, wordable: Verb.create)
Word.create(loc: "ariver", word_definition: WordDefinition.create_or_find_by(definition: "arriver"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to arrive", word_definition: WordDefinition.create_or_find_by(definition: "arriver"), language: lang__en, wordable: Verb.create)
Word.create(loc: "entrar", word_definition: WordDefinition.create_or_find_by(definition: "entrer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "entrer", word_definition: WordDefinition.create_or_find_by(definition: "entrer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to enter", word_definition: WordDefinition.create_or_find_by(definition: "entrer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "venir", word_definition: WordDefinition.create_or_find_by(definition: "venir"), language: lang__es, wordable: Verb.create)
Word.create(loc: "venir", word_definition: WordDefinition.create_or_find_by(definition: "venir"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to come", word_definition: WordDefinition.create_or_find_by(definition: "venir"), language: lang__en, wordable: Verb.create)
Word.create(loc: "viajar", word_definition: WordDefinition.create_or_find_by(definition: "voyager"), language: lang__es, wordable: Verb.create)
Word.create(loc: "voyager", word_definition: WordDefinition.create_or_find_by(definition: "voyager"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to travel", word_definition: WordDefinition.create_or_find_by(definition: "voyager"), language: lang__en, wordable: Verb.create)
Word.create(loc: "visitar", word_definition: WordDefinition.create_or_find_by(definition: "visiter"), language: lang__es, wordable: Verb.create)
Word.create(loc: "visiter", word_definition: WordDefinition.create_or_find_by(definition: "visiter"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to visit", word_definition: WordDefinition.create_or_find_by(definition: "visiter"), language: lang__en, wordable: Verb.create)
Word.create(loc: "pasar", word_definition: WordDefinition.create_or_find_by(definition: "passer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "passer", word_definition: WordDefinition.create_or_find_by(definition: "passer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to spend", word_definition: WordDefinition.create_or_find_by(definition: "passer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "quedar", word_definition: WordDefinition.create_or_find_by(definition: "rester"), language: lang__es, wordable: Verb.create)
Word.create(loc: "rester", word_definition: WordDefinition.create_or_find_by(definition: "rester"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to stay", word_definition: WordDefinition.create_or_find_by(definition: "rester"), language: lang__en, wordable: Verb.create)
Word.create(loc: "volver", word_definition: WordDefinition.create_or_find_by(definition: "retourner"), language: lang__es, wordable: Verb.create)
Word.create(loc: "retourner", word_definition: WordDefinition.create_or_find_by(definition: "retourner"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to return", word_definition: WordDefinition.create_or_find_by(definition: "retourner"), language: lang__en, wordable: Verb.create)
Word.create(loc: "regresar", word_definition: WordDefinition.create_or_find_by(definition: "reculer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "reculer", word_definition: WordDefinition.create_or_find_by(definition: "reculer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to go back", word_definition: WordDefinition.create_or_find_by(definition: "reculer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "desaparecer", word_definition: WordDefinition.create_or_find_by(definition: "disparaître"), language: lang__es, wordable: Verb.create)
Word.create(loc: "disparaître", word_definition: WordDefinition.create_or_find_by(definition: "disparaître"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to disappaer", word_definition: WordDefinition.create_or_find_by(definition: "disparaître"), language: lang__en, wordable: Verb.create)
Word.create(loc: "habitar", word_definition: WordDefinition.create_or_find_by(definition: "habiter"), language: lang__es, wordable: Verb.create)
Word.create(loc: "habiter", word_definition: WordDefinition.create_or_find_by(definition: "habiter"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to inhabit", word_definition: WordDefinition.create_or_find_by(definition: "habiter"), language: lang__en, wordable: Verb.create)
Word.create(loc: "tener", word_definition: WordDefinition.create_or_find_by(definition: "avoir"), language: lang__es, wordable: Verb.create)
Word.create(loc: "avoir", word_definition: WordDefinition.create_or_find_by(definition: "avoir"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to have", word_definition: WordDefinition.create_or_find_by(definition: "avoir"), language: lang__en, wordable: Verb.create)
Word.create(loc: "tener que", word_definition: WordDefinition.create_or_find_by(definition: "devoir"), language: lang__es, wordable: Verb.create)
Word.create(loc: "devoir", word_definition: WordDefinition.create_or_find_by(definition: "devoir"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to have to", word_definition: WordDefinition.create_or_find_by(definition: "devoir"), language: lang__en, wordable: Verb.create)
Word.create(loc: "encontrar", word_definition: WordDefinition.create_or_find_by(definition: "trouver, rencontrer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "trouver", word_definition: WordDefinition.create_or_find_by(definition: "trouver, rencontrer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to find", word_definition: WordDefinition.create_or_find_by(definition: "trouver, rencontrer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "mover", word_definition: WordDefinition.create_or_find_by(definition: "bouger"), language: lang__es, wordable: Verb.create)
Word.create(loc: "bouger", word_definition: WordDefinition.create_or_find_by(definition: "bouger"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to move", word_definition: WordDefinition.create_or_find_by(definition: "bouger"), language: lang__en, wordable: Verb.create)
Word.create(loc: "tomar", word_definition: WordDefinition.create_or_find_by(definition: "prendre"), language: lang__es, wordable: Verb.create)
Word.create(loc: "prendre", word_definition: WordDefinition.create_or_find_by(definition: "prendre"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to take", word_definition: WordDefinition.create_or_find_by(definition: "prendre"), language: lang__en, wordable: Verb.create)
Word.create(loc: "coger", word_definition: WordDefinition.create_or_find_by(definition: "prendre, baiser"), language: lang__es, wordable: Verb.create)
Word.create(loc: "llevar", word_definition: WordDefinition.create_or_find_by(definition: "transporter"), language: lang__es, wordable: Verb.create)
Word.create(loc: "transporter", word_definition: WordDefinition.create_or_find_by(definition: "transporter"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to carry", word_definition: WordDefinition.create_or_find_by(definition: "transporter"), language: lang__en, wordable: Verb.create)
Word.create(loc: "traer", word_definition: WordDefinition.create_or_find_by(definition: "apporter"), language: lang__es, wordable: Verb.create)
Word.create(loc: "apporter", word_definition: WordDefinition.create_or_find_by(definition: "apporter"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to bring", word_definition: WordDefinition.create_or_find_by(definition: "apporter"), language: lang__en, wordable: Verb.create)
Word.create(loc: "enviar", word_definition: WordDefinition.create_or_find_by(definition: "envoyer par la poste"), language: lang__es, wordable: Verb.create)
Word.create(loc: "mandar", word_definition: WordDefinition.create_or_find_by(definition: "demander avec authorité, envoyer quelque part"), language: lang__es, wordable: Verb.create)
Word.create(loc: "envoyer", word_definition: WordDefinition.create_or_find_by(definition: "envoyer par la poste"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "envoyer", word_definition: WordDefinition.create_or_find_by(definition: "demander avec authorité, envoyer quelque part"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to send", word_definition: WordDefinition.create_or_find_by(definition: "envoyer par la poste"), language: lang__en, wordable: Verb.create)
Word.create(loc: "to send", word_definition: WordDefinition.create_or_find_by(definition: "demander avec authorité, envoyer quelque part"), language: lang__en, wordable: Verb.create)
Word.create(loc: "cambiar", word_definition: WordDefinition.create_or_find_by(definition: "changer quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "changer", word_definition: WordDefinition.create_or_find_by(definition: "changer quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to change", word_definition: WordDefinition.create_or_find_by(definition: "changer quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "abrir", word_definition: WordDefinition.create_or_find_by(definition: "ouvrir quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "ouvrir", word_definition: WordDefinition.create_or_find_by(definition: "ouvrir quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to open", word_definition: WordDefinition.create_or_find_by(definition: "ouvrir quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "cerrar", word_definition: WordDefinition.create_or_find_by(definition: "fermer quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "fermer", word_definition: WordDefinition.create_or_find_by(definition: "fermer quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to close", word_definition: WordDefinition.create_or_find_by(definition: "fermer quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "apagar", word_definition: WordDefinition.create_or_find_by(definition: "allumer un appareil, un moteur"), language: lang__es, wordable: Verb.create)
Word.create(loc: "allumer", word_definition: WordDefinition.create_or_find_by(definition: "allumer un appareil, un moteur"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to turn on", word_definition: WordDefinition.create_or_find_by(definition: "allumer un appareil, un moteur"), language: lang__en, wordable: Verb.create)
Word.create(loc: "encender", word_definition: WordDefinition.create_or_find_by(definition: "fermer un appareil, un moteur"), language: lang__es, wordable: Verb.create)
Word.create(loc: "fermer", word_definition: WordDefinition.create_or_find_by(definition: "fermer un appareil, un moteur"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to turn off", word_definition: WordDefinition.create_or_find_by(definition: "fermer un appareil, un moteur"), language: lang__en, wordable: Verb.create)
Word.create(loc: "romper", word_definition: WordDefinition.create_or_find_by(definition: "briser, rompre quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "briser", word_definition: WordDefinition.create_or_find_by(definition: "briser, rompre quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to break", word_definition: WordDefinition.create_or_find_by(definition: "briser, rompre quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "completar", word_definition: WordDefinition.create_or_find_by(definition: "terminer quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "compléter", word_definition: WordDefinition.create_or_find_by(definition: "terminer quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to complete", word_definition: WordDefinition.create_or_find_by(definition: "terminer quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "preparar", word_definition: WordDefinition.create_or_find_by(definition: "préparer quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "préparer", word_definition: WordDefinition.create_or_find_by(definition: "préparer quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to prepare", word_definition: WordDefinition.create_or_find_by(definition: "préparer quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "abalanzar", word_definition: WordDefinition.create_or_find_by(definition: "mettre en équilibre"), language: lang__es, wordable: Verb.create)
Word.create(loc: "équilibrer", word_definition: WordDefinition.create_or_find_by(definition: "mettre en équilibre"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to balance", word_definition: WordDefinition.create_or_find_by(definition: "mettre en équilibre"), language: lang__en, wordable: Verb.create)
Word.create(loc: "abandonar", word_definition: WordDefinition.create_or_find_by(definition: "abandonner"), language: lang__es, wordable: Verb.create)
Word.create(loc: "abandonner", word_definition: WordDefinition.create_or_find_by(definition: "abandonner"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to abandon", word_definition: WordDefinition.create_or_find_by(definition: "abandonner"), language: lang__en, wordable: Verb.create)
Word.create(loc: "abaratar", word_definition: WordDefinition.create_or_find_by(definition: "rendre moins cher"), language: lang__es, wordable: Verb.create)
Word.create(loc: "dévaloriser", word_definition: WordDefinition.create_or_find_by(definition: "rendre moins cher"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to cheapen", word_definition: WordDefinition.create_or_find_by(definition: "rendre moins cher"), language: lang__en, wordable: Verb.create)
Word.create(loc: "abarcar", word_definition: WordDefinition.create_or_find_by(definition: "accepter, inclure"), language: lang__es, wordable: Verb.create)
Word.create(loc: "accepter", word_definition: WordDefinition.create_or_find_by(definition: "accepter, inclure"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to accept", word_definition: WordDefinition.create_or_find_by(definition: "accepter, inclure"), language: lang__en, wordable: Verb.create)
Word.create(loc: "elegir", word_definition: WordDefinition.create_or_find_by(definition: "élire quelque chose, prendre une décision"), language: lang__es, wordable: Verb.create)
Word.create(loc: "choisir", word_definition: WordDefinition.create_or_find_by(definition: "élire quelque chose, prendre une décision"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to chosse", word_definition: WordDefinition.create_or_find_by(definition: "élire quelque chose, prendre une décision"), language: lang__en, wordable: Verb.create)
Word.create(loc: "planear", word_definition: WordDefinition.create_or_find_by(definition: "planifier quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "planifier", word_definition: WordDefinition.create_or_find_by(definition: "planifier quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to plan", word_definition: WordDefinition.create_or_find_by(definition: "planifier quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "hacer", word_definition: WordDefinition.create_or_find_by(definition: "faire une activité"), language: lang__es, wordable: Verb.create)
Word.create(loc: "faire", word_definition: WordDefinition.create_or_find_by(definition: "faire une activité"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to do", word_definition: WordDefinition.create_or_find_by(definition: "faire une activité"), language: lang__en, wordable: Verb.create)
Word.create(loc: "probar", word_definition: WordDefinition.create_or_find_by(definition: "essayer quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "essayer", word_definition: WordDefinition.create_or_find_by(definition: "essayer quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to try", word_definition: WordDefinition.create_or_find_by(definition: "essayer quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "intentar", word_definition: WordDefinition.create_or_find_by(definition: "essayer de faire quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "essayer", word_definition: WordDefinition.create_or_find_by(definition: "essayer de faire quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to try", word_definition: WordDefinition.create_or_find_by(definition: "essayer de faire quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "practicar", word_definition: WordDefinition.create_or_find_by(definition: "pratiquer une activité"), language: lang__es, wordable: Verb.create)
Word.create(loc: "pratiquer", word_definition: WordDefinition.create_or_find_by(definition: "pratiquer une activité"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to practice", word_definition: WordDefinition.create_or_find_by(definition: "pratiquer une activité"), language: lang__en, wordable: Verb.create)
Word.create(loc: "empezar", word_definition: WordDefinition.create_or_find_by(definition: "débuter, commencer quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "commencer", word_definition: WordDefinition.create_or_find_by(definition: "débuter, commencer quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to start", word_definition: WordDefinition.create_or_find_by(definition: "débuter, commencer quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "comenzar", word_definition: WordDefinition.create_or_find_by(definition: "débuter, commencer quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "commencer", word_definition: WordDefinition.create_or_find_by(definition: "débuter, commencer quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to begin", word_definition: WordDefinition.create_or_find_by(definition: "débuter, commencer quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "seguir", word_definition: WordDefinition.create_or_find_by(definition: "continuer quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "continuer", word_definition: WordDefinition.create_or_find_by(definition: "continuer quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to continue", word_definition: WordDefinition.create_or_find_by(definition: "continuer quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "parar", word_definition: WordDefinition.create_or_find_by(definition: "arrêter de faire quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "arrêter", word_definition: WordDefinition.create_or_find_by(definition: "arrêter de faire quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to stop", word_definition: WordDefinition.create_or_find_by(definition: "arrêter de faire quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "esperar", word_definition: WordDefinition.create_or_find_by(definition: "attendre quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "attendre", word_definition: WordDefinition.create_or_find_by(definition: "attendre quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to wait", word_definition: WordDefinition.create_or_find_by(definition: "attendre quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "acabar", word_definition: WordDefinition.create_or_find_by(definition: "finir quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "finir", word_definition: WordDefinition.create_or_find_by(definition: "finir quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to finish", word_definition: WordDefinition.create_or_find_by(definition: "finir quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "repetir", word_definition: WordDefinition.create_or_find_by(definition: "répéter quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "répéter", word_definition: WordDefinition.create_or_find_by(definition: "répéter quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to repeat", word_definition: WordDefinition.create_or_find_by(definition: "répéter quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "ocurrir", word_definition: WordDefinition.create_or_find_by(definition: "lorsque quelque chose se produit"), language: lang__es, wordable: Verb.create)
Word.create(loc: "se produire", word_definition: WordDefinition.create_or_find_by(definition: "lorsque quelque chose se produit"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to occur", word_definition: WordDefinition.create_or_find_by(definition: "lorsque quelque chose se produit"), language: lang__en, wordable: Verb.create)
Word.create(loc: "morir", word_definition: WordDefinition.create_or_find_by(definition: "cesser de vivre"), language: lang__es, wordable: Verb.create)
Word.create(loc: "mourir", word_definition: WordDefinition.create_or_find_by(definition: "cesser de vivre"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to die", word_definition: WordDefinition.create_or_find_by(definition: "cesser de vivre"), language: lang__en, wordable: Verb.create)
Word.create(loc: "sentir", word_definition: WordDefinition.create_or_find_by(definition: "sentir quelque chose par le toucher"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to feel", word_definition: WordDefinition.create_or_find_by(definition: "sentir quelque chose par le toucher"), language: lang__en, wordable: Verb.create)
Word.create(loc: "sentir", word_definition: WordDefinition.create_or_find_by(definition: "sentir quelque chose par le toucher"), language: lang__es, wordable: Verb.create)
Word.create(loc: "être plu par", word_definition: WordDefinition.create_or_find_by(definition: "être plu par quelque chose"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to enjoy", word_definition: WordDefinition.create_or_find_by(definition: "être plu par quelque chose"), language: lang__en, wordable: Verb.create)
Word.create(loc: "gustar", word_definition: WordDefinition.create_or_find_by(definition: "être plu par quelque chose"), language: lang__es, wordable: Verb.create)
Word.create(loc: "pleurer", word_definition: WordDefinition.create_or_find_by(definition: "pleurer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to cry", word_definition: WordDefinition.create_or_find_by(definition: "pleurer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "llorar", word_definition: WordDefinition.create_or_find_by(definition: "pleurer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "se reposer", word_definition: WordDefinition.create_or_find_by(definition: "se reposer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to rest", word_definition: WordDefinition.create_or_find_by(definition: "se reposer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "descansar", word_definition: WordDefinition.create_or_find_by(definition: "se reposer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "dormir", word_definition: WordDefinition.create_or_find_by(definition: "dormir"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to sleep", word_definition: WordDefinition.create_or_find_by(definition: "dormir"), language: lang__en, wordable: Verb.create)
Word.create(loc: "dormir", word_definition: WordDefinition.create_or_find_by(definition: "dormir"), language: lang__es, wordable: Verb.create)
Word.create(loc: "se coucher", word_definition: WordDefinition.create_or_find_by(definition: "aller se coucher"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to go to bed", word_definition: WordDefinition.create_or_find_by(definition: "aller se coucher"), language: lang__en, wordable: Verb.create)
Word.create(loc: "acostar", word_definition: WordDefinition.create_or_find_by(definition: "aller se coucher"), language: lang__es, wordable: Verb.create)
Word.create(loc: "rêver", word_definition: WordDefinition.create_or_find_by(definition: "rêver"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to dream", word_definition: WordDefinition.create_or_find_by(definition: "rêver"), language: lang__en, wordable: Verb.create)
Word.create(loc: "soñar", word_definition: WordDefinition.create_or_find_by(definition: "rêver"), language: lang__es, wordable: Verb.create)
Word.create(loc: "ronfler", word_definition: WordDefinition.create_or_find_by(definition: "ronfler"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to snore", word_definition: WordDefinition.create_or_find_by(definition: "ronfler"), language: lang__en, wordable: Verb.create)
Word.create(loc: "roncar", word_definition: WordDefinition.create_or_find_by(definition: "ronfler"), language: lang__es, wordable: Verb.create)
Word.create(loc: "se réveiller", word_definition: WordDefinition.create_or_find_by(definition: "se réveiller"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to wake up", word_definition: WordDefinition.create_or_find_by(definition: "se réveiller"), language: lang__en, wordable: Verb.create)
Word.create(loc: "despetar", word_definition: WordDefinition.create_or_find_by(definition: "se réveiller"), language: lang__es, wordable: Verb.create)
Word.create(loc: "avoir mal", word_definition: WordDefinition.create_or_find_by(definition: "avoir mal"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to hurt", word_definition: WordDefinition.create_or_find_by(definition: "avoir mal"), language: lang__en, wordable: Verb.create)
Word.create(loc: "doler", word_definition: WordDefinition.create_or_find_by(definition: "avoir mal"), language: lang__es, wordable: Verb.create)
Word.create(loc: "regarder", word_definition: WordDefinition.create_or_find_by(definition: "regarder"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to see", word_definition: WordDefinition.create_or_find_by(definition: "regarder"), language: lang__en, wordable: Verb.create)
Word.create(loc: "mirar", word_definition: WordDefinition.create_or_find_by(definition: "regarder"), language: lang__es, wordable: Verb.create)
Word.create(loc: "regarder", word_definition: WordDefinition.create_or_find_by(definition: "regarder"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to watch", word_definition: WordDefinition.create_or_find_by(definition: "regarder"), language: lang__en, wordable: Verb.create)
Word.create(loc: "ver", word_definition: WordDefinition.create_or_find_by(definition: "regarder"), language: lang__es, wordable: Verb.create)
Word.create(loc: "entendre", word_definition: WordDefinition.create_or_find_by(definition: "entendre"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to hear", word_definition: WordDefinition.create_or_find_by(definition: "entendre"), language: lang__en, wordable: Verb.create)
Word.create(loc: "oír", word_definition: WordDefinition.create_or_find_by(definition: "entendre"), language: lang__es, wordable: Verb.create)
Word.create(loc: "écouter", word_definition: WordDefinition.create_or_find_by(definition: "écouter"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to listen", word_definition: WordDefinition.create_or_find_by(definition: "écouter"), language: lang__en, wordable: Verb.create)
Word.create(loc: "escuchar", word_definition: WordDefinition.create_or_find_by(definition: "écouter"), language: lang__es, wordable: Verb.create)
Word.create(loc: "boire", word_definition: WordDefinition.create_or_find_by(definition: "boire"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to drink", word_definition: WordDefinition.create_or_find_by(definition: "boire"), language: lang__en, wordable: Verb.create)
Word.create(loc: "beber", word_definition: WordDefinition.create_or_find_by(definition: "boire"), language: lang__es, wordable: Verb.create)
Word.create(loc: "manger", word_definition: WordDefinition.create_or_find_by(definition: "manger"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to eat", word_definition: WordDefinition.create_or_find_by(definition: "manger"), language: lang__en, wordable: Verb.create)
Word.create(loc: "comer", word_definition: WordDefinition.create_or_find_by(definition: "manger"), language: lang__es, wordable: Verb.create)
Word.create(loc: "aller dîner", word_definition: WordDefinition.create_or_find_by(definition: "aller dîner"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to have lunch", word_definition: WordDefinition.create_or_find_by(definition: "aller dîner"), language: lang__en, wordable: Verb.create)
Word.create(loc: "almorzar", word_definition: WordDefinition.create_or_find_by(definition: "aller dîner"), language: lang__es, wordable: Verb.create)
Word.create(loc: "souper", word_definition: WordDefinition.create_or_find_by(definition: "souper"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to have dinner", word_definition: WordDefinition.create_or_find_by(definition: "souper"), language: lang__en, wordable: Verb.create)
Word.create(loc: "cenar", word_definition: WordDefinition.create_or_find_by(definition: "souper"), language: lang__es, wordable: Verb.create)
Word.create(loc: "déjeûner", word_definition: WordDefinition.create_or_find_by(definition: "déjeûner"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to have breakfast", word_definition: WordDefinition.create_or_find_by(definition: "déjeûner"), language: lang__en, wordable: Verb.create)
Word.create(loc: "desayunar", word_definition: WordDefinition.create_or_find_by(definition: "déjeûner"), language: lang__es, wordable: Verb.create)
Word.create(loc: "se vêtir", word_definition: WordDefinition.create_or_find_by(definition: "se vêtir"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to dress oneself", word_definition: WordDefinition.create_or_find_by(definition: "se vêtir"), language: lang__en, wordable: Verb.create)
Word.create(loc: "vestir", word_definition: WordDefinition.create_or_find_by(definition: "se vêtir"), language: lang__es, wordable: Verb.create)
Word.create(loc: "aimer", word_definition: WordDefinition.create_or_find_by(definition: "aimer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to love", word_definition: WordDefinition.create_or_find_by(definition: "aimer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "amar", word_definition: WordDefinition.create_or_find_by(definition: "aimer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "apprécier", word_definition: WordDefinition.create_or_find_by(definition: "apprécier"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to enjoy", word_definition: WordDefinition.create_or_find_by(definition: "apprécier"), language: lang__en, wordable: Verb.create)
Word.create(loc: "disfrutar", word_definition: WordDefinition.create_or_find_by(definition: "apprécier"), language: lang__es, wordable: Verb.create)
Word.create(loc: "préférer", word_definition: WordDefinition.create_or_find_by(definition: "préférer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to prefer", word_definition: WordDefinition.create_or_find_by(definition: "préférer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "preferir", word_definition: WordDefinition.create_or_find_by(definition: "préférer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "se préoccuper", word_definition: WordDefinition.create_or_find_by(definition: "se préoccuper"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to worry", word_definition: WordDefinition.create_or_find_by(definition: "se préoccuper"), language: lang__en, wordable: Verb.create)
Word.create(loc: "preocupar", word_definition: WordDefinition.create_or_find_by(definition: "se préoccuper"), language: lang__es, wordable: Verb.create)
Word.create(loc: "haïr", word_definition: WordDefinition.create_or_find_by(definition: "haïr"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to hate", word_definition: WordDefinition.create_or_find_by(definition: "haïr"), language: lang__en, wordable: Verb.create)
Word.create(loc: "odiar", word_definition: WordDefinition.create_or_find_by(definition: "haïr"), language: lang__es, wordable: Verb.create)
Word.create(loc: "s\'ennuyer", word_definition: WordDefinition.create_or_find_by(definition: "s\'ennuyer d"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to miss", word_definition: WordDefinition.create_or_find_by(definition: "s\'ennuyer d"), language: lang__en, wordable: Verb.create)
Word.create(loc: "extrañar", word_definition: WordDefinition.create_or_find_by(definition: "s\'ennuyer d"), language: lang__es, wordable: Verb.create)
Word.create(loc: "penser", word_definition: WordDefinition.create_or_find_by(definition: "penser"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to think", word_definition: WordDefinition.create_or_find_by(definition: "penser"), language: lang__en, wordable: Verb.create)
Word.create(loc: "pensar", word_definition: WordDefinition.create_or_find_by(definition: "penser"), language: lang__es, wordable: Verb.create)
Word.create(loc: "croire", word_definition: WordDefinition.create_or_find_by(definition: "croire"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to believe", word_definition: WordDefinition.create_or_find_by(definition: "croire"), language: lang__en, wordable: Verb.create)
Word.create(loc: "crer", word_definition: WordDefinition.create_or_find_by(definition: "croire"), language: lang__es, wordable: Verb.create)
Word.create(loc: "décider", word_definition: WordDefinition.create_or_find_by(definition: "décider"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to decide", word_definition: WordDefinition.create_or_find_by(definition: "décider"), language: lang__en, wordable: Verb.create)
Word.create(loc: "decidir", word_definition: WordDefinition.create_or_find_by(definition: "décider"), language: lang__es, wordable: Verb.create)
Word.create(loc: "s\'intéresser", word_definition: WordDefinition.create_or_find_by(definition: "s\'intéresser"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to be interested in", word_definition: WordDefinition.create_or_find_by(definition: "s\'intéresser"), language: lang__en, wordable: Verb.create)
Word.create(loc: "interesar", word_definition: WordDefinition.create_or_find_by(definition: "s\'intéresser"), language: lang__es, wordable: Verb.create)
Word.create(loc: "apprendre", word_definition: WordDefinition.create_or_find_by(definition: "apprendre"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to learn", word_definition: WordDefinition.create_or_find_by(definition: "apprendre"), language: lang__en, wordable: Verb.create)
Word.create(loc: "aprendar", word_definition: WordDefinition.create_or_find_by(definition: "apprendre"), language: lang__es, wordable: Verb.create)
Word.create(loc: "étudier", word_definition: WordDefinition.create_or_find_by(definition: "étudier"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to study", word_definition: WordDefinition.create_or_find_by(definition: "étudier"), language: lang__en, wordable: Verb.create)
Word.create(loc: "estudiar", word_definition: WordDefinition.create_or_find_by(definition: "étudier"), language: lang__es, wordable: Verb.create)
Word.create(loc: "enseigner", word_definition: WordDefinition.create_or_find_by(definition: "enseigner"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to teach", word_definition: WordDefinition.create_or_find_by(definition: "enseigner"), language: lang__en, wordable: Verb.create)
Word.create(loc: "enseñar", word_definition: WordDefinition.create_or_find_by(definition: "enseigner"), language: lang__es, wordable: Verb.create)
Word.create(loc: "se rappeller", word_definition: WordDefinition.create_or_find_by(definition: "se rappeller"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to remember", word_definition: WordDefinition.create_or_find_by(definition: "se rappeller"), language: lang__en, wordable: Verb.create)
Word.create(loc: "recordar", word_definition: WordDefinition.create_or_find_by(definition: "se rappeller"), language: lang__es, wordable: Verb.create)
Word.create(loc: "comprendre", word_definition: WordDefinition.create_or_find_by(definition: "comprendre"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to understand", word_definition: WordDefinition.create_or_find_by(definition: "comprendre"), language: lang__en, wordable: Verb.create)
Word.create(loc: "entender", word_definition: WordDefinition.create_or_find_by(definition: "comprendre"), language: lang__es, wordable: Verb.create)
Word.create(loc: "comprendre", word_definition: WordDefinition.create_or_find_by(definition: "comprendre"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to understand", word_definition: WordDefinition.create_or_find_by(definition: "comprendre"), language: lang__en, wordable: Verb.create)
Word.create(loc: "comprender", word_definition: WordDefinition.create_or_find_by(definition: "comprendre"), language: lang__es, wordable: Verb.create)
Word.create(loc: "oublier", word_definition: WordDefinition.create_or_find_by(definition: "oublier"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to forget", word_definition: WordDefinition.create_or_find_by(definition: "oublier"), language: lang__en, wordable: Verb.create)
Word.create(loc: "olvidar", word_definition: WordDefinition.create_or_find_by(definition: "oublier"), language: lang__es, wordable: Verb.create)
Word.create(loc: "avoir besoin de", word_definition: WordDefinition.create_or_find_by(definition: "avoir besoin de"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to need", word_definition: WordDefinition.create_or_find_by(definition: "avoir besoin de"), language: lang__en, wordable: Verb.create)
Word.create(loc: "necesitar", word_definition: WordDefinition.create_or_find_by(definition: "avoir besoin de"), language: lang__es, wordable: Verb.create)
Word.create(loc: "chercher", word_definition: WordDefinition.create_or_find_by(definition: "chercher"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to look for", word_definition: WordDefinition.create_or_find_by(definition: "chercher"), language: lang__en, wordable: Verb.create)
Word.create(loc: "buscar", word_definition: WordDefinition.create_or_find_by(definition: "chercher"), language: lang__es, wordable: Verb.create)
Word.create(loc: "demander", word_definition: WordDefinition.create_or_find_by(definition: "demander, passer un"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to order", word_definition: WordDefinition.create_or_find_by(definition: "demander, passer un"), language: lang__en, wordable: Verb.create)
Word.create(loc: "pedir", word_definition: WordDefinition.create_or_find_by(definition: "demander, passer un"), language: lang__es, wordable: Verb.create)
Word.create(loc: "servir", word_definition: WordDefinition.create_or_find_by(definition: "servir (un repas, un"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to serve", word_definition: WordDefinition.create_or_find_by(definition: "servir (un repas, un"), language: lang__en, wordable: Verb.create)
Word.create(loc: "servir", word_definition: WordDefinition.create_or_find_by(definition: "servir (un repas, un"), language: lang__es, wordable: Verb.create)
Word.create(loc: "fournir", word_definition: WordDefinition.create_or_find_by(definition: "fournir"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to supply", word_definition: WordDefinition.create_or_find_by(definition: "fournir"), language: lang__en, wordable: Verb.create)
Word.create(loc: "abastecer", word_definition: WordDefinition.create_or_find_by(definition: "fournir"), language: lang__es, wordable: Verb.create)
Word.create(loc: "prendre une douche", word_definition: WordDefinition.create_or_find_by(definition: "prendre une douche"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to shower", word_definition: WordDefinition.create_or_find_by(definition: "prendre une douche"), language: lang__en, wordable: Verb.create)
Word.create(loc: "duchar", word_definition: WordDefinition.create_or_find_by(definition: "prendre une douche"), language: lang__es, wordable: Verb.create)
Word.create(loc: "laver", word_definition: WordDefinition.create_or_find_by(definition: "laver (quelqu\'un)"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to wash", word_definition: WordDefinition.create_or_find_by(definition: "laver (quelqu\'un)"), language: lang__en, wordable: Verb.create)
Word.create(loc: "lavar", word_definition: WordDefinition.create_or_find_by(definition: "laver (quelqu\'un)"), language: lang__es, wordable: Verb.create)
Word.create(loc: "laver", word_definition: WordDefinition.create_or_find_by(definition: "laver (quelque chose)"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to clean", word_definition: WordDefinition.create_or_find_by(definition: "laver (quelque chose)"), language: lang__en, wordable: Verb.create)
Word.create(loc: "limpiar", word_definition: WordDefinition.create_or_find_by(definition: "laver (quelque chose)"), language: lang__es, wordable: Verb.create)
Word.create(loc: "s\'occuper de", word_definition: WordDefinition.create_or_find_by(definition: "s\'occuper de"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to take care of", word_definition: WordDefinition.create_or_find_by(definition: "s\'occuper de"), language: lang__en, wordable: Verb.create)
Word.create(loc: "cuidar", word_definition: WordDefinition.create_or_find_by(definition: "s\'occuper de"), language: lang__es, wordable: Verb.create)
Word.create(loc: "brosser", word_definition: WordDefinition.create_or_find_by(definition: "brosser"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to brush", word_definition: WordDefinition.create_or_find_by(definition: "brosser"), language: lang__en, wordable: Verb.create)
Word.create(loc: "cepillar", word_definition: WordDefinition.create_or_find_by(definition: "brosser"), language: lang__es, wordable: Verb.create)
Word.create(loc: "réparer", word_definition: WordDefinition.create_or_find_by(definition: "réprarer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to repair", word_definition: WordDefinition.create_or_find_by(definition: "réprarer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "reparar", word_definition: WordDefinition.create_or_find_by(definition: "réprarer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "porter", word_definition: WordDefinition.create_or_find_by(definition: "porter (vêtement)"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to wear", word_definition: WordDefinition.create_or_find_by(definition: "porter (vêtement)"), language: lang__en, wordable: Verb.create)
Word.create(loc: "usar", word_definition: WordDefinition.create_or_find_by(definition: "porter (vêtement)"), language: lang__es, wordable: Verb.create)
Word.create(loc: "utiliser", word_definition: WordDefinition.create_or_find_by(definition: "utiliser"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to use", word_definition: WordDefinition.create_or_find_by(definition: "utiliser"), language: lang__en, wordable: Verb.create)
Word.create(loc: "usar", word_definition: WordDefinition.create_or_find_by(definition: "utiliser"), language: lang__es, wordable: Verb.create)
Word.create(loc: "mettre", word_definition: WordDefinition.create_or_find_by(definition: "mettre (vêtement)"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to put on", word_definition: WordDefinition.create_or_find_by(definition: "mettre (vêtement)"), language: lang__en, wordable: Verb.create)
Word.create(loc: "poner", word_definition: WordDefinition.create_or_find_by(definition: "mettre (vêtement)"), language: lang__es, wordable: Verb.create)
Word.create(loc: "parler", word_definition: WordDefinition.create_or_find_by(definition: "parler"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to speak", word_definition: WordDefinition.create_or_find_by(definition: "parler"), language: lang__en, wordable: Verb.create)
Word.create(loc: "hablar", word_definition: WordDefinition.create_or_find_by(definition: "parler"), language: lang__es, wordable: Verb.create)
Word.create(loc: "lire", word_definition: WordDefinition.create_or_find_by(definition: "lire"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to read", word_definition: WordDefinition.create_or_find_by(definition: "lire"), language: lang__en, wordable: Verb.create)
Word.create(loc: "leer", word_definition: WordDefinition.create_or_find_by(definition: "lire"), language: lang__es, wordable: Verb.create)
Word.create(loc: "jouer", word_definition: WordDefinition.create_or_find_by(definition: "jouer (d\'un instrumen"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to play", word_definition: WordDefinition.create_or_find_by(definition: "jouer (d\'un instrumen"), language: lang__en, wordable: Verb.create)
Word.create(loc: "tocar", word_definition: WordDefinition.create_or_find_by(definition: "jouer (d\'un instrumen"), language: lang__es, wordable: Verb.create)
Word.create(loc: "fumer", word_definition: WordDefinition.create_or_find_by(definition: "fumer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to smoke", word_definition: WordDefinition.create_or_find_by(definition: "fumer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "fumar", word_definition: WordDefinition.create_or_find_by(definition: "fumer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "conduire", word_definition: WordDefinition.create_or_find_by(definition: "conduire (un véhicule)"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to drive", word_definition: WordDefinition.create_or_find_by(definition: "conduire (un véhicule)"), language: lang__en, wordable: Verb.create)
Word.create(loc: "manejar", word_definition: WordDefinition.create_or_find_by(definition: "conduire (un véhicule)"), language: lang__es, wordable: Verb.create)
Word.create(loc: "monter", word_definition: WordDefinition.create_or_find_by(definition: "monter (un véhicule"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to ride", word_definition: WordDefinition.create_or_find_by(definition: "monter (un véhicule"), language: lang__en, wordable: Verb.create)
Word.create(loc: "montar", word_definition: WordDefinition.create_or_find_by(definition: "monter (un véhicule"), language: lang__es, wordable: Verb.create)
Word.create(loc: "ventiler", word_definition: WordDefinition.create_or_find_by(definition: "ventiler"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to fan", word_definition: WordDefinition.create_or_find_by(definition: "ventiler"), language: lang__en, wordable: Verb.create)
Word.create(loc: "abanicar", word_definition: WordDefinition.create_or_find_by(definition: "ventiler"), language: lang__es, wordable: Verb.create)
Word.create(loc: "donner", word_definition: WordDefinition.create_or_find_by(definition: "donner"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to give", word_definition: WordDefinition.create_or_find_by(definition: "donner"), language: lang__en, wordable: Verb.create)
Word.create(loc: "dar", word_definition: WordDefinition.create_or_find_by(definition: "donner"), language: lang__es, wordable: Verb.create)
Word.create(loc: "recevoir", word_definition: WordDefinition.create_or_find_by(definition: "recevoir"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to receive", word_definition: WordDefinition.create_or_find_by(definition: "recevoir"), language: lang__en, wordable: Verb.create)
Word.create(loc: "recivir", word_definition: WordDefinition.create_or_find_by(definition: "recevoir"), language: lang__es, wordable: Verb.create)
Word.create(loc: "payer", word_definition: WordDefinition.create_or_find_by(definition: "payer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to pay", word_definition: WordDefinition.create_or_find_by(definition: "payer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "pagar", word_definition: WordDefinition.create_or_find_by(definition: "payer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "acheter", word_definition: WordDefinition.create_or_find_by(definition: "acheter"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to buy", word_definition: WordDefinition.create_or_find_by(definition: "acheter"), language: lang__en, wordable: Verb.create)
Word.create(loc: "comprar", word_definition: WordDefinition.create_or_find_by(definition: "acheter"), language: lang__es, wordable: Verb.create)
Word.create(loc: "réserver", word_definition: WordDefinition.create_or_find_by(definition: "réserver"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to reserve", word_definition: WordDefinition.create_or_find_by(definition: "réserver"), language: lang__en, wordable: Verb.create)
Word.create(loc: "reservar", word_definition: WordDefinition.create_or_find_by(definition: "réserver"), language: lang__es, wordable: Verb.create)
Word.create(loc: "pêcher", word_definition: WordDefinition.create_or_find_by(definition: "pêcher"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to fish", word_definition: WordDefinition.create_or_find_by(definition: "pêcher"), language: lang__en, wordable: Verb.create)
Word.create(loc: "pescar", word_definition: WordDefinition.create_or_find_by(definition: "pêcher"), language: lang__es, wordable: Verb.create)
Word.create(loc: "inviter", word_definition: WordDefinition.create_or_find_by(definition: "inviter"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to invite", word_definition: WordDefinition.create_or_find_by(definition: "inviter"), language: lang__en, wordable: Verb.create)
Word.create(loc: "invitar", word_definition: WordDefinition.create_or_find_by(definition: "inviter"), language: lang__es, wordable: Verb.create)
Word.create(loc: "connaître", word_definition: WordDefinition.create_or_find_by(definition: "connaître (quelqu\'un)"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to know", word_definition: WordDefinition.create_or_find_by(definition: "connaître (quelqu\'un)"), language: lang__en, wordable: Verb.create)
Word.create(loc: "conocer", word_definition: WordDefinition.create_or_find_by(definition: "connaître (quelqu\'un)"), language: lang__es, wordable: Verb.create)
Word.create(loc: "rencontrer", word_definition: WordDefinition.create_or_find_by(definition: "rencontrer (quelqu\'u"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to meet", word_definition: WordDefinition.create_or_find_by(definition: "rencontrer (quelqu\'u"), language: lang__en, wordable: Verb.create)
Word.create(loc: "encontrar", word_definition: WordDefinition.create_or_find_by(definition: "rencontrer (quelqu\'u"), language: lang__es, wordable: Verb.create)
Word.create(loc: "rejoindre", word_definition: WordDefinition.create_or_find_by(definition: "rejoindre"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to meet up", word_definition: WordDefinition.create_or_find_by(definition: "rejoindre"), language: lang__en, wordable: Verb.create)
Word.create(loc: "quedar", word_definition: WordDefinition.create_or_find_by(definition: "rejoindre"), language: lang__es, wordable: Verb.create)
Word.create(loc: "accompagner", word_definition: WordDefinition.create_or_find_by(definition: "accompagner"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to go along with", word_definition: WordDefinition.create_or_find_by(definition: "accompagner"), language: lang__en, wordable: Verb.create)
Word.create(loc: "acompañar", word_definition: WordDefinition.create_or_find_by(definition: "accompagner"), language: lang__es, wordable: Verb.create)
Word.create(loc: "demander", word_definition: WordDefinition.create_or_find_by(definition: "demander"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to ask", word_definition: WordDefinition.create_or_find_by(definition: "demander"), language: lang__en, wordable: Verb.create)
Word.create(loc: "preguntar", word_definition: WordDefinition.create_or_find_by(definition: "demander"), language: lang__es, wordable: Verb.create)
Word.create(loc: "répondre", word_definition: WordDefinition.create_or_find_by(definition: "répondre"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to answer", word_definition: WordDefinition.create_or_find_by(definition: "répondre"), language: lang__en, wordable: Verb.create)
Word.create(loc: "responder", word_definition: WordDefinition.create_or_find_by(definition: "répondre"), language: lang__es, wordable: Verb.create)
Word.create(loc: "dire", word_definition: WordDefinition.create_or_find_by(definition: "dire"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to tell", word_definition: WordDefinition.create_or_find_by(definition: "dire"), language: lang__en, wordable: Verb.create)
Word.create(loc: "decir", word_definition: WordDefinition.create_or_find_by(definition: "dire"), language: lang__es, wordable: Verb.create)
Word.create(loc: "appeller", word_definition: WordDefinition.create_or_find_by(definition: "appeller"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to call", word_definition: WordDefinition.create_or_find_by(definition: "appeller"), language: lang__en, wordable: Verb.create)
Word.create(loc: "llamar", word_definition: WordDefinition.create_or_find_by(definition: "appeller"), language: lang__es, wordable: Verb.create)
Word.create(loc: "avoir une conversation", word_definition: WordDefinition.create_or_find_by(definition: "avoir une conversation"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to chat", word_definition: WordDefinition.create_or_find_by(definition: "avoir une conversation"), language: lang__en, wordable: Verb.create)
Word.create(loc: "conversar", word_definition: WordDefinition.create_or_find_by(definition: "avoir une conversation"), language: lang__es, wordable: Verb.create)
Word.create(loc: "arrimer", word_definition: WordDefinition.create_or_find_by(definition: "arrimer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to stow", word_definition: WordDefinition.create_or_find_by(definition: "arrimer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "abarrotar", word_definition: WordDefinition.create_or_find_by(definition: "arrimer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "écrire", word_definition: WordDefinition.create_or_find_by(definition: "écrire"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to write", word_definition: WordDefinition.create_or_find_by(definition: "écrire"), language: lang__en, wordable: Verb.create)
Word.create(loc: "escribir", word_definition: WordDefinition.create_or_find_by(definition: "écrire"), language: lang__es, wordable: Verb.create)
Word.create(loc: "cuisiner", word_definition: WordDefinition.create_or_find_by(definition: "cuisiner"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to cook", word_definition: WordDefinition.create_or_find_by(definition: "cuisiner"), language: lang__en, wordable: Verb.create)
Word.create(loc: "cocinar", word_definition: WordDefinition.create_or_find_by(definition: "cuisiner"), language: lang__es, wordable: Verb.create)
Word.create(loc: "dessiner", word_definition: WordDefinition.create_or_find_by(definition: "dessiner"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to draw", word_definition: WordDefinition.create_or_find_by(definition: "dessiner"), language: lang__en, wordable: Verb.create)
Word.create(loc: "dibujar", word_definition: WordDefinition.create_or_find_by(definition: "dessiner"), language: lang__es, wordable: Verb.create)
Word.create(loc: "peinturer", word_definition: WordDefinition.create_or_find_by(definition: "peinturer"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to paint", word_definition: WordDefinition.create_or_find_by(definition: "peinturer"), language: lang__en, wordable: Verb.create)
Word.create(loc: "pintar", word_definition: WordDefinition.create_or_find_by(definition: "peinturer"), language: lang__es, wordable: Verb.create)
Word.create(loc: "chanter", word_definition: WordDefinition.create_or_find_by(definition: "chanter"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to sing", word_definition: WordDefinition.create_or_find_by(definition: "chanter"), language: lang__en, wordable: Verb.create)
Word.create(loc: "cantar", word_definition: WordDefinition.create_or_find_by(definition: "chanter"), language: lang__es, wordable: Verb.create)
Word.create(loc: "travailler", word_definition: WordDefinition.create_or_find_by(definition: "travailler"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to work", word_definition: WordDefinition.create_or_find_by(definition: "travailler"), language: lang__en, wordable: Verb.create)
Word.create(loc: "trabajar", word_definition: WordDefinition.create_or_find_by(definition: "travailler"), language: lang__es, wordable: Verb.create)
Word.create(loc: "jouer", word_definition: WordDefinition.create_or_find_by(definition: "jouer (à un jeu)"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to play", word_definition: WordDefinition.create_or_find_by(definition: "jouer (à un jeu)"), language: lang__en, wordable: Verb.create)
Word.create(loc: "jugar", word_definition: WordDefinition.create_or_find_by(definition: "jouer (à un jeu)"), language: lang__es, wordable: Verb.create)
Word.create(loc: "passer", word_definition: WordDefinition.create_or_find_by(definition: "passer (un examen)"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to pass", word_definition: WordDefinition.create_or_find_by(definition: "passer (un examen)"), language: lang__en, wordable: Verb.create)
Word.create(loc: "aprobar", word_definition: WordDefinition.create_or_find_by(definition: "passer (un examen)"), language: lang__es, wordable: Verb.create)
Word.create(loc: "gagner", word_definition: WordDefinition.create_or_find_by(definition: "gagner"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to win", word_definition: WordDefinition.create_or_find_by(definition: "gagner"), language: lang__en, wordable: Verb.create)
Word.create(loc: "ganar", word_definition: WordDefinition.create_or_find_by(definition: "gagner"), language: lang__es, wordable: Verb.create)
Word.create(loc: "perdre", word_definition: WordDefinition.create_or_find_by(definition: "perdre"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to lose", word_definition: WordDefinition.create_or_find_by(definition: "perdre"), language: lang__en, wordable: Verb.create)
Word.create(loc: "perder", word_definition: WordDefinition.create_or_find_by(definition: "perdre"), language: lang__es, wordable: Verb.create)
Word.create(loc: "prier", word_definition: WordDefinition.create_or_find_by(definition: "prier"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to pray", word_definition: WordDefinition.create_or_find_by(definition: "prier"), language: lang__en, wordable: Verb.create)
Word.create(loc: "rezar", word_definition: WordDefinition.create_or_find_by(definition: "prier"), language: lang__es, wordable: Verb.create)
Word.create(loc: "empoisonner", word_definition: WordDefinition.create_or_find_by(definition: "empoisonner"), language: lang__fr, wordable: Verb.create)
Word.create(loc: "to poison", word_definition: WordDefinition.create_or_find_by(definition: "empoisonner"), language: lang__en, wordable: Verb.create)
Word.create(loc: "envenenar", word_definition: WordDefinition.create_or_find_by(definition: "empoisonner"), language: lang__es, wordable: Verb.create)