lang__en = Language.find_by({name: 'English', shorthand: 'en', active: true})
lang__fr = Language.find_by({name: 'Français', shorthand: 'fr', active: true})
lang__es = Language.find_by({name: 'Español', shorthand: 'es', active: true})
lang__ca = Language.find_by({name: 'Catalan', shorthand: 'ca', active: true})
lang__no = Language.find_by({name: 'Norsk', shorthand: 'no', active: true})


Word.create(loc: "où", word_definition: WordDefinition.create_or_find_by(definition: "où"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "where", word_definition: WordDefinition.create_or_find_by(definition: "où"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "dónde", word_definition: WordDefinition.create_or_find_by(definition: "où"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "quand", word_definition: WordDefinition.create_or_find_by(definition: "quand"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "when", word_definition: WordDefinition.create_or_find_by(definition: "quand"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "cuándo", word_definition: WordDefinition.create_or_find_by(definition: "quand"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "qu\'est-ce", word_definition: WordDefinition.create_or_find_by(definition: "what, quel/qu\'est-ce"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "what", word_definition: WordDefinition.create_or_find_by(definition: "what, quel/qu\'est-ce"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "qué", word_definition: WordDefinition.create_or_find_by(definition: "what, quel/qu\'est-ce"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "qui", word_definition: WordDefinition.create_or_find_by(definition: "qui"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "who", word_definition: WordDefinition.create_or_find_by(definition: "qui"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "quién", word_definition: WordDefinition.create_or_find_by(definition: "qui"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "pourquoi", word_definition: WordDefinition.create_or_find_by(definition: "pourquoi"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "why", word_definition: WordDefinition.create_or_find_by(definition: "pourquoi"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "por qué", word_definition: WordDefinition.create_or_find_by(definition: "pourquoi"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "lequel", word_definition: WordDefinition.create_or_find_by(definition: "lequel"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "which", word_definition: WordDefinition.create_or_find_by(definition: "lequel"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "cuál", word_definition: WordDefinition.create_or_find_by(definition: "lequel"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "combien", word_definition: WordDefinition.create_or_find_by(definition: "combien (inquantifiable)"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "how much", word_definition: WordDefinition.create_or_find_by(definition: "combien (inquantifiable)"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "cuánto", word_definition: WordDefinition.create_or_find_by(definition: "combien (inquantifiable)"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "combien", word_definition: WordDefinition.create_or_find_by(definition: "combien (quantifiable)"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "how many", word_definition: WordDefinition.create_or_find_by(definition: "combien (quantifiable)"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "cuántas", word_definition: WordDefinition.create_or_find_by(definition: "combien (quantifiable)"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "comment", word_definition: WordDefinition.create_or_find_by(definition: "comment"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "how", word_definition: WordDefinition.create_or_find_by(definition: "comment"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "cómo", word_definition: WordDefinition.create_or_find_by(definition: "comment"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "ici", word_definition: WordDefinition.create_or_find_by(definition: "ici"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "here", word_definition: WordDefinition.create_or_find_by(definition: "ici"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "aqui", word_definition: WordDefinition.create_or_find_by(definition: "ici"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "proche", word_definition: WordDefinition.create_or_find_by(definition: "proche, pas loin"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "nearby", word_definition: WordDefinition.create_or_find_by(definition: "proche, pas loin"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "acá", word_definition: WordDefinition.create_or_find_by(definition: "proche, pas loin"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "par là", word_definition: WordDefinition.create_or_find_by(definition: "par là"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "over there", word_definition: WordDefinition.create_or_find_by(definition: "par là"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "allá", word_definition: WordDefinition.create_or_find_by(definition: "par là"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "là", word_definition: WordDefinition.create_or_find_by(definition: "là, là-bas"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "there", word_definition: WordDefinition.create_or_find_by(definition: "là, là-bas"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "allí", word_definition: WordDefinition.create_or_find_by(definition: "là, là-bas"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "là-bas", word_definition: WordDefinition.create_or_find_by(definition: "là, là-bas"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "there", word_definition: WordDefinition.create_or_find_by(definition: "là, là-bas"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "ahí", word_definition: WordDefinition.create_or_find_by(definition: "là, là-bas"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "partout", word_definition: WordDefinition.create_or_find_by(definition: "partout"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "everywhere", word_definition: WordDefinition.create_or_find_by(definition: "partout"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "en todas partes", word_definition: WordDefinition.create_or_find_by(definition: "partout"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "proche", word_definition: WordDefinition.create_or_find_by(definition: "près de, proche de"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "near", word_definition: WordDefinition.create_or_find_by(definition: "près de, proche de"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "cerca", word_definition: WordDefinition.create_or_find_by(definition: "près de, proche de"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "à côté de", word_definition: WordDefinition.create_or_find_by(definition: "à côté de"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "next to", word_definition: WordDefinition.create_or_find_by(definition: "à côté de"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "al lado", word_definition: WordDefinition.create_or_find_by(definition: "à côté de"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "loin", word_definition: WordDefinition.create_or_find_by(definition: "lointain, loin"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "far", word_definition: WordDefinition.create_or_find_by(definition: "lointain, loin"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "lejos", word_definition: WordDefinition.create_or_find_by(definition: "lointain, loin"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "à l\'intérieur", word_definition: WordDefinition.create_or_find_by(definition: "à l\'intérieur, en dedans"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "inside", word_definition: WordDefinition.create_or_find_by(definition: "à l\'intérieur, en dedans"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "adentro", word_definition: WordDefinition.create_or_find_by(definition: "à l\'intérieur, en dedans"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "par dessus", word_definition: WordDefinition.create_or_find_by(definition: "par dessus"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "on (top of)", word_definition: WordDefinition.create_or_find_by(definition: "par dessus"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "sobre", word_definition: WordDefinition.create_or_find_by(definition: "par dessus"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "par dessus", word_definition: WordDefinition.create_or_find_by(definition: "par dessus, en haut de"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "on top of", word_definition: WordDefinition.create_or_find_by(definition: "par dessus, en haut de"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "encíma", word_definition: WordDefinition.create_or_find_by(definition: "par dessus, en haut de"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "sous", word_definition: WordDefinition.create_or_find_by(definition: "sous, en dessous"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "under", word_definition: WordDefinition.create_or_find_by(definition: "sous, en dessous"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "debajo", word_definition: WordDefinition.create_or_find_by(definition: "sous, en dessous"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "derrière", word_definition: WordDefinition.create_or_find_by(definition: "derrière"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "behind", word_definition: WordDefinition.create_or_find_by(definition: "derrière"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "detrás", word_definition: WordDefinition.create_or_find_by(definition: "derrière"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "en avant", word_definition: WordDefinition.create_or_find_by(definition: "en avant de, devant"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "in front of", word_definition: WordDefinition.create_or_find_by(definition: "en avant de, devant"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "enfrente", word_definition: WordDefinition.create_or_find_by(definition: "en avant de, devant"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "entre", word_definition: WordDefinition.create_or_find_by(definition: "entre"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "between", word_definition: WordDefinition.create_or_find_by(definition: "entre"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "entre", word_definition: WordDefinition.create_or_find_by(definition: "entre"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "dans", word_definition: WordDefinition.create_or_find_by(definition: "dans, à l\'intérieur"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "inside", word_definition: WordDefinition.create_or_find_by(definition: "dans, à l\'intérieur"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "dentro", word_definition: WordDefinition.create_or_find_by(definition: "dans, à l\'intérieur"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "en bas", word_definition: WordDefinition.create_or_find_by(definition: "en bas"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "downstairs", word_definition: WordDefinition.create_or_find_by(definition: "en bas"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "abajo", word_definition: WordDefinition.create_or_find_by(definition: "en bas"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "en haut", word_definition: WordDefinition.create_or_find_by(definition: "en haut"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "upstairs", word_definition: WordDefinition.create_or_find_by(definition: "en haut"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "arriba", word_definition: WordDefinition.create_or_find_by(definition: "en haut"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "en arrière", word_definition: WordDefinition.create_or_find_by(definition: "en arrière"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "in the back", word_definition: WordDefinition.create_or_find_by(definition: "en arrière"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "atrás", word_definition: WordDefinition.create_or_find_by(definition: "en arrière"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "dehors", word_definition: WordDefinition.create_or_find_by(definition: "dehors, à l\'extérieur"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "outside", word_definition: WordDefinition.create_or_find_by(definition: "dehors, à l\'extérieur"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "fuera", word_definition: WordDefinition.create_or_find_by(definition: "dehors, à l\'extérieur"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "à travers", word_definition: WordDefinition.create_or_find_by(definition: "à travers"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "through", word_definition: WordDefinition.create_or_find_by(definition: "à travers"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "por", word_definition: WordDefinition.create_or_find_by(definition: "à travers"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "le long de", word_definition: WordDefinition.create_or_find_by(definition: "le long de"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "along", word_definition: WordDefinition.create_or_find_by(definition: "le long de"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "por", word_definition: WordDefinition.create_or_find_by(definition: "le long de"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "vers", word_definition: WordDefinition.create_or_find_by(definition: "vers"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "around", word_definition: WordDefinition.create_or_find_by(definition: "vers"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "por", word_definition: WordDefinition.create_or_find_by(definition: "vers"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "par ici", word_definition: WordDefinition.create_or_find_by(definition: "par ici"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "this way", word_definition: WordDefinition.create_or_find_by(definition: "par ici"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "por aquí", word_definition: WordDefinition.create_or_find_by(definition: "par ici"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "très", word_definition: WordDefinition.create_or_find_by(definition: "très"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "very", word_definition: WordDefinition.create_or_find_by(definition: "très"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "muy", word_definition: WordDefinition.create_or_find_by(definition: "très"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "plus", word_definition: WordDefinition.create_or_find_by(definition: "plus, une plus grande quantité"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "more", word_definition: WordDefinition.create_or_find_by(definition: "plus, une plus grande quantité"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "más", word_definition: WordDefinition.create_or_find_by(definition: "plus, une plus grande quantité"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "extra", word_definition: WordDefinition.create_or_find_by(definition: "extra"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "extra", word_definition: WordDefinition.create_or_find_by(definition: "extra"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "extra", word_definition: WordDefinition.create_or_find_by(definition: "extra"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "trop", word_definition: WordDefinition.create_or_find_by(definition: "trop"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "too/too much/too many", word_definition: WordDefinition.create_or_find_by(definition: "trop"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "demasiado", word_definition: WordDefinition.create_or_find_by(definition: "trop"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "beaucoup", word_definition: WordDefinition.create_or_find_by(definition: "beaucoup"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "a lot", word_definition: WordDefinition.create_or_find_by(definition: "beaucoup"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "mucho", word_definition: WordDefinition.create_or_find_by(definition: "beaucoup"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "peu", word_definition: WordDefinition.create_or_find_by(definition: "peu"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "few", word_definition: WordDefinition.create_or_find_by(definition: "peu"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "poco", word_definition: WordDefinition.create_or_find_by(definition: "peu"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "plusieurs", word_definition: WordDefinition.create_or_find_by(definition: "plusieurs"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "many", word_definition: WordDefinition.create_or_find_by(definition: "plusieurs"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "varios", word_definition: WordDefinition.create_or_find_by(definition: "plusieurs"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "quelques", word_definition: WordDefinition.create_or_find_by(definition: "quelques"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "some", word_definition: WordDefinition.create_or_find_by(definition: "quelques"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "unas", word_definition: WordDefinition.create_or_find_by(definition: "quelques"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "les deux", word_definition: WordDefinition.create_or_find_by(definition: "les deux"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "both", word_definition: WordDefinition.create_or_find_by(definition: "les deux"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "ambas", word_definition: WordDefinition.create_or_find_by(definition: "les deux"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "complètement", word_definition: WordDefinition.create_or_find_by(definition: "complètement"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "completely", word_definition: WordDefinition.create_or_find_by(definition: "complètement"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "completamente", word_definition: WordDefinition.create_or_find_by(definition: "complètement"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "aucun", word_definition: WordDefinition.create_or_find_by(definition: "aucun"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "none", word_definition: WordDefinition.create_or_find_by(definition: "aucun"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "ninguno", word_definition: WordDefinition.create_or_find_by(definition: "aucun"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "quelque", word_definition: WordDefinition.create_or_find_by(definition: "quelque"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "some", word_definition: WordDefinition.create_or_find_by(definition: "quelque"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "algún", word_definition: WordDefinition.create_or_find_by(definition: "quelque"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "quelques", word_definition: WordDefinition.create_or_find_by(definition: "quelques"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "some", word_definition: WordDefinition.create_or_find_by(definition: "quelques"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "algunos", word_definition: WordDefinition.create_or_find_by(definition: "quelques"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "presque", word_definition: WordDefinition.create_or_find_by(definition: "presque"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "almost", word_definition: WordDefinition.create_or_find_by(definition: "presque"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "casi", word_definition: WordDefinition.create_or_find_by(definition: "presque"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "maintenant", word_definition: WordDefinition.create_or_find_by(definition: "maintenant"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "now", word_definition: WordDefinition.create_or_find_by(definition: "maintenant"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "ahora", word_definition: WordDefinition.create_or_find_by(definition: "maintenant"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "une autre fois", word_definition: WordDefinition.create_or_find_by(definition: "une autre fois"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "another time", word_definition: WordDefinition.create_or_find_by(definition: "une autre fois"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "otra vez", word_definition: WordDefinition.create_or_find_by(definition: "une autre fois"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "cette fois-ci", word_definition: WordDefinition.create_or_find_by(definition: "cette fois-ci"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "this time", word_definition: WordDefinition.create_or_find_by(definition: "cette fois-ci"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "esta vez", word_definition: WordDefinition.create_or_find_by(definition: "cette fois-ci"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "en ce moment même", word_definition: WordDefinition.create_or_find_by(definition: "en ce moment même"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "right now", word_definition: WordDefinition.create_or_find_by(definition: "en ce moment même"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "ahora mismo", word_definition: WordDefinition.create_or_find_by(definition: "en ce moment même"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "un jour", word_definition: WordDefinition.create_or_find_by(definition: "un jour"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "someday", word_definition: WordDefinition.create_or_find_by(definition: "un jour"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "algun día", word_definition: WordDefinition.create_or_find_by(definition: "un jour"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "tout le temps", word_definition: WordDefinition.create_or_find_by(definition: "tout le temps"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "all the time", word_definition: WordDefinition.create_or_find_by(definition: "tout le temps"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "todo el tiempo", word_definition: WordDefinition.create_or_find_by(definition: "tout le temps"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "il y a longtemps", word_definition: WordDefinition.create_or_find_by(definition: "il y a longtemps"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "a long time ago", word_definition: WordDefinition.create_or_find_by(definition: "il y a longtemps"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "hace mucho tiempo", word_definition: WordDefinition.create_or_find_by(definition: "il y a longtemps"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "puis", word_definition: WordDefinition.create_or_find_by(definition: "et puis, après"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "then", word_definition: WordDefinition.create_or_find_by(definition: "et puis, après"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "entonces", word_definition: WordDefinition.create_or_find_by(definition: "et puis, après"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "avant", word_definition: WordDefinition.create_or_find_by(definition: "avant, précédemment"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "before", word_definition: WordDefinition.create_or_find_by(definition: "avant, précédemment"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "antes", word_definition: WordDefinition.create_or_find_by(definition: "avant, précédemment"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "après", word_definition: WordDefinition.create_or_find_by(definition: "après, ensuite"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "after", word_definition: WordDefinition.create_or_find_by(definition: "après, ensuite"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "después", word_definition: WordDefinition.create_or_find_by(definition: "après, ensuite"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "autour de", word_definition: WordDefinition.create_or_find_by(definition: "autour de (temps)"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "around", word_definition: WordDefinition.create_or_find_by(definition: "autour de (temps)"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "sobre", word_definition: WordDefinition.create_or_find_by(definition: "autour de (temps)"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "pour", word_definition: WordDefinition.create_or_find_by(definition: "pour (échéance)"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "for", word_definition: WordDefinition.create_or_find_by(definition: "pour (échéance)"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "para", word_definition: WordDefinition.create_or_find_by(definition: "pour (échéance)"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "plus", word_definition: WordDefinition.create_or_find_by(definition: "plus (elle ne fait plus quelque chose)"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "no more", word_definition: WordDefinition.create_or_find_by(definition: "plus (elle ne fait plus quelque chose)"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "más", word_definition: WordDefinition.create_or_find_by(definition: "plus (elle ne fait plus quelque chose)"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "qui vient", word_definition: WordDefinition.create_or_find_by(definition: "qui vient"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "next", word_definition: WordDefinition.create_or_find_by(definition: "qui vient"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "que viene", word_definition: WordDefinition.create_or_find_by(definition: "qui vient"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "prochain", word_definition: WordDefinition.create_or_find_by(definition: "prochain"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "next", word_definition: WordDefinition.create_or_find_by(definition: "prochain"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "siguiente", word_definition: WordDefinition.create_or_find_by(definition: "prochain"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "plus tard", word_definition: WordDefinition.create_or_find_by(definition: "plus tard"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "later", word_definition: WordDefinition.create_or_find_by(definition: "plus tard"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "luego", word_definition: WordDefinition.create_or_find_by(definition: "plus tard"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "passé", word_definition: WordDefinition.create_or_find_by(definition: "dernier, passé"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "last", word_definition: WordDefinition.create_or_find_by(definition: "dernier, passé"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "pasada", word_definition: WordDefinition.create_or_find_by(definition: "dernier, passé"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "premier", word_definition: WordDefinition.create_or_find_by(definition: "premier"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "first", word_definition: WordDefinition.create_or_find_by(definition: "premier"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "primero", word_definition: WordDefinition.create_or_find_by(definition: "premier"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "tôt", word_definition: WordDefinition.create_or_find_by(definition: "tôt"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "early", word_definition: WordDefinition.create_or_find_by(definition: "tôt"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "temprano", word_definition: WordDefinition.create_or_find_by(definition: "tôt"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "tard", word_definition: WordDefinition.create_or_find_by(definition: "tard"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "late", word_definition: WordDefinition.create_or_find_by(definition: "tard"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "tarde", word_definition: WordDefinition.create_or_find_by(definition: "tard"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "bientôt", word_definition: WordDefinition.create_or_find_by(definition: "bientôt"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "soon", word_definition: WordDefinition.create_or_find_by(definition: "bientôt"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "pronto", word_definition: WordDefinition.create_or_find_by(definition: "bientôt"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "il y a", word_definition: WordDefinition.create_or_find_by(definition: "il y a (temps dans le passé)"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "ago", word_definition: WordDefinition.create_or_find_by(definition: "il y a (temps dans le passé)"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "hace", word_definition: WordDefinition.create_or_find_by(definition: "il y a (temps dans le passé)"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "finalement", word_definition: WordDefinition.create_or_find_by(definition: "finalement, pour finir"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "finally", word_definition: WordDefinition.create_or_find_by(definition: "finalement, pour finir"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "por fin", word_definition: WordDefinition.create_or_find_by(definition: "finalement, pour finir"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "jamais", word_definition: WordDefinition.create_or_find_by(definition: "jamais"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "never", word_definition: WordDefinition.create_or_find_by(definition: "jamais"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "nunca", word_definition: WordDefinition.create_or_find_by(definition: "jamais"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "jamais", word_definition: WordDefinition.create_or_find_by(definition: "jamais"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "never", word_definition: WordDefinition.create_or_find_by(definition: "jamais"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "jamás", word_definition: WordDefinition.create_or_find_by(definition: "jamais"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "desfois", word_definition: WordDefinition.create_or_find_by(definition: "desfois"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "sometimes", word_definition: WordDefinition.create_or_find_by(definition: "desfois"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "a veces", word_definition: WordDefinition.create_or_find_by(definition: "desfois"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "de temps en temps", word_definition: WordDefinition.create_or_find_by(definition: "de temps en temps"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "once in a while", word_definition: WordDefinition.create_or_find_by(definition: "de temps en temps"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "de vez en cuando", word_definition: WordDefinition.create_or_find_by(definition: "de temps en temps"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "normalement", word_definition: WordDefinition.create_or_find_by(definition: "normalement"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "normally", word_definition: WordDefinition.create_or_find_by(definition: "normalement"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "normalemente", word_definition: WordDefinition.create_or_find_by(definition: "normalement"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "d\'habitude", word_definition: WordDefinition.create_or_find_by(definition: "d\'habitude, habituellement"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "usually", word_definition: WordDefinition.create_or_find_by(definition: "d\'habitude, habituellement"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "usualmente", word_definition: WordDefinition.create_or_find_by(definition: "d\'habitude, habituellement"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "généralement", word_definition: WordDefinition.create_or_find_by(definition: "généralement"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "generally", word_definition: WordDefinition.create_or_find_by(definition: "généralement"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "generalmente", word_definition: WordDefinition.create_or_find_by(definition: "généralement"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "fréquemment", word_definition: WordDefinition.create_or_find_by(definition: "fréquemment"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "frequently", word_definition: WordDefinition.create_or_find_by(definition: "fréquemment"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "frecuentemente", word_definition: WordDefinition.create_or_find_by(definition: "fréquemment"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "souvent", word_definition: WordDefinition.create_or_find_by(definition: "souvent"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "often", word_definition: WordDefinition.create_or_find_by(definition: "souvent"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "a menudo", word_definition: WordDefinition.create_or_find_by(definition: "souvent"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "toujours", word_definition: WordDefinition.create_or_find_by(definition: "toujours, tout le temps, en tout temps"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "always", word_definition: WordDefinition.create_or_find_by(definition: "toujours, tout le temps, en tout temps"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "siempre", word_definition: WordDefinition.create_or_find_by(definition: "toujours, tout le temps, en tout temps"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "plus ... que", word_definition: WordDefinition.create_or_find_by(definition: "être plus <...> que"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "more ... than", word_definition: WordDefinition.create_or_find_by(definition: "être plus <...> que"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "más ... que", word_definition: WordDefinition.create_or_find_by(definition: "être plus <...> que"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "moins ... que", word_definition: WordDefinition.create_or_find_by(definition: "moins <...> que"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "less ... than", word_definition: WordDefinition.create_or_find_by(definition: "moins <...> que"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "menos ... que", word_definition: WordDefinition.create_or_find_by(definition: "moins <...> que"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "autant ... que", word_definition: WordDefinition.create_or_find_by(definition: "autant <...> que"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "as ... as", word_definition: WordDefinition.create_or_find_by(definition: "autant <...> que"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "tan ... como", word_definition: WordDefinition.create_or_find_by(definition: "autant <...> que"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "la plus", word_definition: WordDefinition.create_or_find_by(definition: "le/la plus"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "the most", word_definition: WordDefinition.create_or_find_by(definition: "le/la plus"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "la más", word_definition: WordDefinition.create_or_find_by(definition: "le/la plus"), language: lang__es, wordable: Adverb.create)
Word.create(loc: "lentement", word_definition: WordDefinition.create_or_find_by(definition: "avec lenteur"), language: lang__fr, wordable: Adverb.create)
Word.create(loc: "slowly", word_definition: WordDefinition.create_or_find_by(definition: "avec lenteur"), language: lang__en, wordable: Adverb.create)
Word.create(loc: "despacio", word_definition: WordDefinition.create_or_find_by(definition: "avec lenteur"), language: lang__es, wordable: Adverb.create)