lang__en = Language.find_by({name: 'English', shorthand: 'en', active: true})
lang__fr = Language.find_by({name: 'Français', shorthand: 'fr', active: true})
lang__es = Language.find_by({name: 'Español', shorthand: 'es', active: true})
lang__ca = Language.find_by({name: 'Catalan', shorthand: 'ca', active: true})
lang__no = Language.find_by({name: 'Norsk', shorthand: 'no', active: true})

gender__neutral = Gender.find_by(name: "Neutral", shorthand: "n")
gender__male = Gender.find_by(name: "Male", shorthand: "m")
gender__female = Gender.find_by(name: "Female", shorthand: "f")
gender__object = Gender.find_by(name: "Object", shorthand: "o")
gender__plural = Gender.find_by(name: "Plural", shorthand: "p")
gender__mixed = Gender.find_by(name: "Mixed", shorthand: "all")
gender__unknown = Gender.find_by(name: "Unknown", shorthand: "un")

=begin
    # template
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))

=end 

Word.create(loc: "mot", word_definition: WordDefinition.create_or_find_by(definition: "ensemble de lettres organisées dans un ordre donné, qui a une signification quelconque dans un language donné"), language: lang__fr, wordable: Noun.create(gender: gender__male))
Word.create(loc: "word", word_definition: WordDefinition.create_or_find_by(definition: "ensemble de lettres organisées dans un ordre donné, qui a une signification quelconque dans un language donné"), language: lang__en, wordable: Noun.create)
Word.create(loc: "palabra", word_definition: WordDefinition.create_or_find_by(definition: "ensemble de lettres organisées dans un ordre donné, qui a une signification quelconque dans un language donné"), language: lang__es, wordable: Noun.create(gender: gender__female))
Word.create(loc: "chose", word_definition: WordDefinition.create_or_find_by(definition: "un objet quelconque"), language: lang__fr, wordable: Noun.create(gender: gender__female))
Word.create(loc: "thing", word_definition: WordDefinition.create_or_find_by(definition: "un objet quelconque"), language: lang__en, wordable: Noun.create)
Word.create(loc: "cosa", word_definition: WordDefinition.create_or_find_by(definition: "un objet quelconque"), language: lang__es, wordable: Noun.create(gender: gender__female))
Word.create(loc: "monde", word_definition: WordDefinition.create_or_find_by(definition: "ensemble de tout ce qui existe"), language: lang__fr, wordable: Noun.create(gender: gender__male))
Word.create(loc: "world", word_definition: WordDefinition.create_or_find_by(definition: "ensemble de tout ce qui existe"), language: lang__en, wordable: Noun.create)
Word.create(loc: "mundo", word_definition: WordDefinition.create_or_find_by(definition: "ensemble de tout ce qui existe"), language: lang__es, wordable: Noun.create(gender: gender__male))
Word.create(loc: "vide", word_definition: WordDefinition.create_or_find_by(definition: "néant; absence de toute chose, nulle part"), language: lang__fr, wordable: Noun.create(gender: gender__male))
Word.create(loc: "nothingness", word_definition: WordDefinition.create_or_find_by(definition: "néant; absence de toute chose, nulle part"), language: lang__en, wordable: Noun.create)
Word.create(loc: "nada", word_definition: WordDefinition.create_or_find_by(definition: "néant; absence de toute chose, nulle part"), language: lang__es, wordable: Noun.create(gender: gender__female))
Word.create(loc: "vérité", word_definition: WordDefinition.create_or_find_by(definition: "connaissance conforme au réel"), language: lang__fr, wordable: Noun.create(gender: gender__female))
Word.create(loc: "truth", word_definition: WordDefinition.create_or_find_by(definition: "connaissance conforme au réel"), language: lang__en, wordable: Noun.create)
Word.create(loc: "verdad", word_definition: WordDefinition.create_or_find_by(definition: "connaissance conforme au réel"), language: lang__es, wordable: Noun.create(gender: gender__female))
Word.create(loc: "idée", word_definition: WordDefinition.create_or_find_by(definition: "représentation par la pensée"), language: lang__fr, wordable: Noun.create(gender: gender__female))
Word.create(loc: "idea", word_definition: WordDefinition.create_or_find_by(definition: "représentation par la pensée"), language: lang__en, wordable: Noun.create)
Word.create(loc: "idea", word_definition: WordDefinition.create_or_find_by(definition: "représentation par la pensée"), language: lang__es, wordable: Noun.create(gender: gender__female))
Word.create(loc: "magie", word_definition: WordDefinition.create_or_find_by(definition: "art de produire des phénomènes occultes"), language: lang__fr, wordable: Noun.create(gender: gender__female))
Word.create(loc: "magic", word_definition: WordDefinition.create_or_find_by(definition: "art de produire des phénomènes occultes"), language: lang__en, wordable: Noun.create)
Word.create(loc: "magia", word_definition: WordDefinition.create_or_find_by(definition: "art de produire des phénomènes occultes"), language: lang__es, wordable: Noun.create(gender: gender__female))
Word.create(loc: "raison", word_definition: WordDefinition.create_or_find_by(definition: "faculté de connaître, juger, déduire par raisonnement"), language: lang__fr, wordable: Noun.create(gender: gender__female))
Word.create(loc: "reason", word_definition: WordDefinition.create_or_find_by(definition: "faculté de connaître, juger, déduire par raisonnement"), language: lang__en, wordable: Noun.create)
Word.create(loc: "rázon", word_definition: WordDefinition.create_or_find_by(definition: "faculté de connaître, juger, déduire par raisonnement"), language: lang__es, wordable: Noun.create(gender: gender__female))
Word.create(loc: "début", word_definition: WordDefinition.create_or_find_by(definition: "commencement"), language: lang__fr, wordable: Noun.create(gender: gender__male))
Word.create(loc: "beginning", word_definition: WordDefinition.create_or_find_by(definition: "commencement"), language: lang__en, wordable: Noun.create)
Word.create(loc: "principio", word_definition: WordDefinition.create_or_find_by(definition: "commencement"), language: lang__es, wordable: Noun.create(gender: gender__male))
Word.create(loc: "problème", word_definition: WordDefinition.create_or_find_by(definition: "difficulté, obstacle empêchant le bon fonctionnement de quelque chose; question à régler"), language: lang__fr, wordable: Noun.create(gender: gender__male))
Word.create(loc: "problem", word_definition: WordDefinition.create_or_find_by(definition: "difficulté, obstacle empêchant le bon fonctionnement de quelque chose; question à régler"), language: lang__en, wordable: Noun.create)
Word.create(loc: "problema", word_definition: WordDefinition.create_or_find_by(definition: "difficulté, obstacle empêchant le bon fonctionnement de quelque chose; question à régler"), language: lang__es, wordable: Noun.create(gender: gender__female))
Word.create(loc: "thème", word_definition: WordDefinition.create_or_find_by(definition: "sujet, idée, proposition développée; dessin mélodique"), language: lang__fr, wordable: Noun.create(gender: gender__male))
Word.create(loc: "theme", word_definition: WordDefinition.create_or_find_by(definition: "sujet, idée, proposition développée; dessin mélodique"), language: lang__en, wordable: Noun.create)
Word.create(loc: "tema", word_definition: WordDefinition.create_or_find_by(definition: "sujet, idée, proposition développée; dessin mélodique"), language: lang__es, wordable: Noun.create(gender: gender__female))
Word.create(loc: "sujet", word_definition: WordDefinition.create_or_find_by(definition: "ce sur quoi porte une discussion ou réflexion"), language: lang__fr, wordable: Noun.create(gender: gender__male))
Word.create(loc: "subject", word_definition: WordDefinition.create_or_find_by(definition: "ce sur quoi porte une discussion ou réflexion"), language: lang__en, wordable: Noun.create)
Word.create(loc: "asignatura", word_definition: WordDefinition.create_or_find_by(definition: "ce sur quoi porte une discussion ou réflexion"), language: lang__es, wordable: Noun.create(gender: gender__female))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__fr, wordable: Noun.create(gender: gender_))
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__en, wordable: Noun.create)
Word.create(loc: "", word_definition: WordDefinition.create_or_find_by(definition: ""), language: lang__es, wordable: Noun.create(gender: gender_))